//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public enum VrstaPotrditve {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("4")]
    Item4,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("12")]
    Item12,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("27")]
    Item27,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("29")]
    Item29,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("-99")]
    Item99,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public enum VrstaPodatkaPodjetja {
    
    /// <remarks/>
    AP,
    
    /// <remarks/>
    API,
    
    /// <remarks/>
    GN,
    
    /// <remarks/>
    IA,
    
    /// <remarks/>
    IT,
    
    /// <remarks/>
    PY,
    
    /// <remarks/>
    VA,
    
    /// <remarks/>
    XA,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public enum VrstaPartnerja {
    
    /// <remarks/>
    BY,
    
    /// <remarks/>
    DP,
    
    /// <remarks/>
    OB,
    
    /// <remarks/>
    SU,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public enum VrstaKomunikacije {
    
    /// <remarks/>
    EM,
    
    /// <remarks/>
    FX,
    
    /// <remarks/>
    TE,
    
    /// <remarks/>
    TL,
    
    /// <remarks/>
    XF,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public enum VrstaDokumenta {
    
    /// <remarks/>
    DESADV,
    
    /// <remarks/>
    INVOIC,
    
    /// <remarks/>
    ORDERS,
    
    /// <remarks/>
    ORDRSP,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public enum VrstaDatuma {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("137")]
    Item137,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("310")]
    Item310,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class Ulica {
    
    private string ulica1Field;
    
    private string ulica2Field;
    
    private string ulica3Field;
    
    private string ulica4Field;
    
    /// <remarks/>
    public string Ulica1 {
        get {
            return this.ulica1Field;
        }
        set {
            this.ulica1Field = value;
        }
    }
    
    /// <remarks/>
    public string Ulica2 {
        get {
            return this.ulica2Field;
        }
        set {
            this.ulica2Field = value;
        }
    }
    
    /// <remarks/>
    public string Ulica3 {
        get {
            return this.ulica3Field;
        }
        set {
            this.ulica3Field = value;
        }
    }
    
    /// <remarks/>
    public string Ulica4 {
        get {
            return this.ulica4Field;
        }
        set {
            this.ulica4Field = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public enum TipOsebe {
    
    /// <remarks/>
    AA,
    
    /// <remarks/>
    AD,
    
    /// <remarks/>
    AM,
    
    /// <remarks/>
    AP,
    
    /// <remarks/>
    AR,
    
    /// <remarks/>
    BC,
    
    /// <remarks/>
    CB,
    
    /// <remarks/>
    CN,
    
    /// <remarks/>
    CO,
    
    /// <remarks/>
    CR,
    
    /// <remarks/>
    DE,
    
    /// <remarks/>
    DI,
    
    /// <remarks/>
    DL,
    
    /// <remarks/>
    ED,
    
    /// <remarks/>
    GR,
    
    /// <remarks/>
    HE,
    
    /// <remarks/>
    HG,
    
    /// <remarks/>
    IC,
    
    /// <remarks/>
    LO,
    
    /// <remarks/>
    NT,
    
    /// <remarks/>
    OC,
    
    /// <remarks/>
    ODP,
    
    /// <remarks/>
    PD,
    
    /// <remarks/>
    PM,
    
    /// <remarks/>
    QC,
    
    /// <remarks/>
    SA,
    
    /// <remarks/>
    SD,
    
    /// <remarks/>
    SR,
    
    /// <remarks/>
    TD,
    
    /// <remarks/>
    WH,
    
    /// <remarks/>
    ZZZ,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class ReferencniPodatkiPodjetja {
    
    private VrstaPodatkaPodjetja vrstaPodatkaPodjetjaField;
    
    private bool vrstaPodatkaPodjetjaFieldSpecified;
    
    private string podatekPodjetjaField;
    
    /// <remarks/>
    public VrstaPodatkaPodjetja VrstaPodatkaPodjetja {
        get {
            return this.vrstaPodatkaPodjetjaField;
        }
        set {
            this.vrstaPodatkaPodjetjaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool VrstaPodatkaPodjetjaSpecified {
        get {
            return this.vrstaPodatkaPodjetjaFieldSpecified;
        }
        set {
            this.vrstaPodatkaPodjetjaFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string PodatekPodjetja {
        get {
            return this.podatekPodjetjaField;
        }
        set {
            this.podatekPodjetjaField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class Povratnica {
    
    private OdgovorNaSporocilo odgovorNaSporociloField;
    
    private OdgovorNaDokument[] odgovorNaDokumentField;
    
    /// <remarks/>
    public OdgovorNaSporocilo OdgovorNaSporocilo {
        get {
            return this.odgovorNaSporociloField;
        }
        set {
            this.odgovorNaSporociloField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("OdgovorNaDokument")]
    public OdgovorNaDokument[] OdgovorNaDokument {
        get {
            return this.odgovorNaDokumentField;
        }
        set {
            this.odgovorNaDokumentField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class OdgovorNaSporocilo {
    
    private PodatkiPodjetja[] podatkiPodjetjaField;
    
    private VrstaPotrditve vrstaPotrditveField;
    
    private long stevilkaSporocilaField;
    
    private string opisField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("PodatkiPodjetja")]
    public PodatkiPodjetja[] PodatkiPodjetja {
        get {
            return this.podatkiPodjetjaField;
        }
        set {
            this.podatkiPodjetjaField = value;
        }
    }
    
    /// <remarks/>
    public VrstaPotrditve VrstaPotrditve {
        get {
            return this.vrstaPotrditveField;
        }
        set {
            this.vrstaPotrditveField = value;
        }
    }
    
    /// <remarks/>
    public long StevilkaSporocila {
        get {
            return this.stevilkaSporocilaField;
        }
        set {
            this.stevilkaSporocilaField = value;
        }
    }
    
    /// <remarks/>
    public string Opis {
        get {
            return this.opisField;
        }
        set {
            this.opisField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class PodatkiPodjetja {
    
    private NazivNaslovPodjetja nazivNaslovPodjetjaField;
    
    private ReferencniPodatkiPodjetja[] referencniPodatkiPodjetjaField;
    
    private KontaktiPodjetja[] kontaktiPodjetjaField;
    
    /// <remarks/>
    public NazivNaslovPodjetja NazivNaslovPodjetja {
        get {
            return this.nazivNaslovPodjetjaField;
        }
        set {
            this.nazivNaslovPodjetjaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ReferencniPodatkiPodjetja")]
    public ReferencniPodatkiPodjetja[] ReferencniPodatkiPodjetja {
        get {
            return this.referencniPodatkiPodjetjaField;
        }
        set {
            this.referencniPodatkiPodjetjaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("KontaktiPodjetja")]
    public KontaktiPodjetja[] KontaktiPodjetja {
        get {
            return this.kontaktiPodjetjaField;
        }
        set {
            this.kontaktiPodjetjaField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class NazivNaslovPodjetja {
    
    private VrstaPartnerja vrstaPartnerjaField;
    
    private bool vrstaPartnerjaFieldSpecified;
    
    private IdentifikacijaPartnerja identifikacijaPartnerjaField;
    
    private NazivPartnerja nazivPartnerjaField;
    
    private Ulica ulicaField;
    
    private string krajField;
    
    private string nazivDrzaveField;
    
    private string postnaStevilkaField;
    
    private string kodaDrzaveField;
    
    /// <remarks/>
    public VrstaPartnerja VrstaPartnerja {
        get {
            return this.vrstaPartnerjaField;
        }
        set {
            this.vrstaPartnerjaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool VrstaPartnerjaSpecified {
        get {
            return this.vrstaPartnerjaFieldSpecified;
        }
        set {
            this.vrstaPartnerjaFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public IdentifikacijaPartnerja IdentifikacijaPartnerja {
        get {
            return this.identifikacijaPartnerjaField;
        }
        set {
            this.identifikacijaPartnerjaField = value;
        }
    }
    
    /// <remarks/>
    public NazivPartnerja NazivPartnerja {
        get {
            return this.nazivPartnerjaField;
        }
        set {
            this.nazivPartnerjaField = value;
        }
    }
    
    /// <remarks/>
    public Ulica Ulica {
        get {
            return this.ulicaField;
        }
        set {
            this.ulicaField = value;
        }
    }
    
    /// <remarks/>
    public string Kraj {
        get {
            return this.krajField;
        }
        set {
            this.krajField = value;
        }
    }
    
    /// <remarks/>
    public string NazivDrzave {
        get {
            return this.nazivDrzaveField;
        }
        set {
            this.nazivDrzaveField = value;
        }
    }
    
    /// <remarks/>
    public string PostnaStevilka {
        get {
            return this.postnaStevilkaField;
        }
        set {
            this.postnaStevilkaField = value;
        }
    }
    
    /// <remarks/>
    public string KodaDrzave {
        get {
            return this.kodaDrzaveField;
        }
        set {
            this.kodaDrzaveField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class IdentifikacijaPartnerja {
    
    private string stevilkaPartnerjaField;
    
    private Agencija agencijaField;
    
    private bool agencijaFieldSpecified;
    
    /// <remarks/>
    public string StevilkaPartnerja {
        get {
            return this.stevilkaPartnerjaField;
        }
        set {
            this.stevilkaPartnerjaField = value;
        }
    }
    
    /// <remarks/>
    public Agencija Agencija {
        get {
            return this.agencijaField;
        }
        set {
            this.agencijaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool AgencijaSpecified {
        get {
            return this.agencijaFieldSpecified;
        }
        set {
            this.agencijaFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public enum Agencija {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("9")]
    Item9,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("91")]
    Item91,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("92")]
    Item92,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class NazivPartnerja {
    
    private string nazivPartnerja1Field;
    
    private string nazivPartnerja2Field;
    
    private string nazivPartnerja3Field;
    
    private string nazivPartnerja4Field;
    
    /// <remarks/>
    public string NazivPartnerja1 {
        get {
            return this.nazivPartnerja1Field;
        }
        set {
            this.nazivPartnerja1Field = value;
        }
    }
    
    /// <remarks/>
    public string NazivPartnerja2 {
        get {
            return this.nazivPartnerja2Field;
        }
        set {
            this.nazivPartnerja2Field = value;
        }
    }
    
    /// <remarks/>
    public string NazivPartnerja3 {
        get {
            return this.nazivPartnerja3Field;
        }
        set {
            this.nazivPartnerja3Field = value;
        }
    }
    
    /// <remarks/>
    public string NazivPartnerja4 {
        get {
            return this.nazivPartnerja4Field;
        }
        set {
            this.nazivPartnerja4Field = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class KontaktiPodjetja {
    
    private KontaktnaOseba kontaktnaOsebaField;
    
    private Komunikacije[] komunikacijeField;
    
    /// <remarks/>
    public KontaktnaOseba KontaktnaOseba {
        get {
            return this.kontaktnaOsebaField;
        }
        set {
            this.kontaktnaOsebaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Komunikacije")]
    public Komunikacije[] Komunikacije {
        get {
            return this.komunikacijeField;
        }
        set {
            this.komunikacijeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class KontaktnaOseba {
    
    private TipOsebe tipOsebeField;
    
    private bool tipOsebeFieldSpecified;
    
    private string imeOsebeField;
    
    /// <remarks/>
    public TipOsebe TipOsebe {
        get {
            return this.tipOsebeField;
        }
        set {
            this.tipOsebeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool TipOsebeSpecified {
        get {
            return this.tipOsebeFieldSpecified;
        }
        set {
            this.tipOsebeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string ImeOsebe {
        get {
            return this.imeOsebeField;
        }
        set {
            this.imeOsebeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class Komunikacije {
    
    private string stevilkaKomunikacijeField;
    
    private VrstaKomunikacije vrstaKomunikacijeField;
    
    /// <remarks/>
    public string StevilkaKomunikacije {
        get {
            return this.stevilkaKomunikacijeField;
        }
        set {
            this.stevilkaKomunikacijeField = value;
        }
    }
    
    /// <remarks/>
    public VrstaKomunikacije VrstaKomunikacije {
        get {
            return this.vrstaKomunikacijeField;
        }
        set {
            this.vrstaKomunikacijeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class OdgovorNaDokument {
    
    private Dokument dokumentField;
    
    private DatumiDokumenta[] datumiDokumentaField;
    
    /// <remarks/>
    public Dokument Dokument {
        get {
            return this.dokumentField;
        }
        set {
            this.dokumentField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("DatumiDokumenta")]
    public DatumiDokumenta[] DatumiDokumenta {
        get {
            return this.datumiDokumentaField;
        }
        set {
            this.datumiDokumentaField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class Dokument {
    
    private string stevilkaDokumentaField;
    
    private VrstaDokumenta vrstaDokumentaField;
    
    private bool vrstaDokumentaFieldSpecified;
    
    /// <remarks/>
    public string StevilkaDokumenta {
        get {
            return this.stevilkaDokumentaField;
        }
        set {
            this.stevilkaDokumentaField = value;
        }
    }
    
    /// <remarks/>
    public VrstaDokumenta VrstaDokumenta {
        get {
            return this.vrstaDokumentaField;
        }
        set {
            this.vrstaDokumentaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool VrstaDokumentaSpecified {
        get {
            return this.vrstaDokumentaFieldSpecified;
        }
        set {
            this.vrstaDokumentaFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class DatumiDokumenta {
    
    private VrstaDatuma vrstaDatumaField;
    
    private System.DateTime datumDokumentaField;
    
    private bool datumDokumentaFieldSpecified;
    
    /// <remarks/>
    public VrstaDatuma VrstaDatuma {
        get {
            return this.vrstaDatumaField;
        }
        set {
            this.vrstaDatumaField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime DatumDokumenta {
        get {
            return this.datumDokumentaField;
        }
        set {
            this.datumDokumentaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool DatumDokumentaSpecified {
        get {
            return this.datumDokumentaFieldSpecified;
        }
        set {
            this.datumDokumentaFieldSpecified = value;
        }
    }
}
