//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KomunikatorEGP.ws_Inf_EvidencaMM
{


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace = "http://servis.EvidencaMMDobaviteljWS.informatika.si/", ConfigurationName = "ws_Inf_EvidencaMM.EvidencaMMDobaviteljWS")]
    public interface EvidencaMMDobaviteljWS
    {

        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action = "", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name = "return")]
        KomunikatorEGP.ws_Inf_EvidencaMM.najdiEvidencoResponse najdiEvidenco(KomunikatorEGP.ws_Inf_EvidencaMM.najdiEvidencoRequest request);

        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action = "", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name = "return")]
        KomunikatorEGP.ws_Inf_EvidencaMM.najdiEvidencoPodrobnostiResponse najdiEvidencoPodrobnosti(KomunikatorEGP.ws_Inf_EvidencaMM.najdiEvidencoPodrobnostiRequest request);

        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action = "", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name = "return")]
        KomunikatorEGP.ws_Inf_EvidencaMM.najdiSeznamEvidencResponse najdiSeznamEvidenc(KomunikatorEGP.ws_Inf_EvidencaMM.najdiSeznamEvidencRequest request);

        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action = "", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name = "return")]
        KomunikatorEGP.ws_Inf_EvidencaMM.oddajEvidencoResponse oddajEvidenco(KomunikatorEGP.ws_Inf_EvidencaMM.oddajEvidencoRequest request);
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://servis.EvidencaMMDobaviteljWS.informatika.si/")]
    public partial class evidencaOdgovor : object, System.ComponentModel.INotifyPropertyChanged
    {

        private System.DateTime datumOddajeEvidenceField;

        private bool datumOddajeEvidenceFieldSpecified;

        private System.DateTime datumOdobritveEvidenceField;

        private bool datumOdobritveEvidenceFieldSpecified;

        private System.DateTime datumSpremembeField;

        private bool datumSpremembeFieldSpecified;

        private short disField;

        private int idField;

        private dokument[] meritveField;

        private string msgField;

        private dokument[] narocilniceField;

        private dokument[] pooblastilaField;

        private int rcField;

        private bool rcFieldSpecified;

        private int sifraDobaviteljaField;

        private bool sifraDobaviteljaFieldSpecified;

        private int smmField;

        private string statusEvidenceField;

        private string vrstaStoritveField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public System.DateTime datumOddajeEvidence
        {
            get
            {
                return this.datumOddajeEvidenceField;
            }
            set
            {
                this.datumOddajeEvidenceField = value;
                this.RaisePropertyChanged("datumOddajeEvidence");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool datumOddajeEvidenceSpecified
        {
            get
            {
                return this.datumOddajeEvidenceFieldSpecified;
            }
            set
            {
                this.datumOddajeEvidenceFieldSpecified = value;
                this.RaisePropertyChanged("datumOddajeEvidenceSpecified");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public System.DateTime datumOdobritveEvidence
        {
            get
            {
                return this.datumOdobritveEvidenceField;
            }
            set
            {
                this.datumOdobritveEvidenceField = value;
                this.RaisePropertyChanged("datumOdobritveEvidence");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool datumOdobritveEvidenceSpecified
        {
            get
            {
                return this.datumOdobritveEvidenceFieldSpecified;
            }
            set
            {
                this.datumOdobritveEvidenceFieldSpecified = value;
                this.RaisePropertyChanged("datumOdobritveEvidenceSpecified");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
        public System.DateTime datumSpremembe
        {
            get
            {
                return this.datumSpremembeField;
            }
            set
            {
                this.datumSpremembeField = value;
                this.RaisePropertyChanged("datumSpremembe");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool datumSpremembeSpecified
        {
            get
            {
                return this.datumSpremembeFieldSpecified;
            }
            set
            {
                this.datumSpremembeFieldSpecified = value;
                this.RaisePropertyChanged("datumSpremembeSpecified");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 3)]
        public short dis
        {
            get
            {
                return this.disField;
            }
            set
            {
                this.disField = value;
                this.RaisePropertyChanged("dis");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 4)]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("meritve", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true, Order = 5)]
        public dokument[] meritve
        {
            get
            {
                return this.meritveField;
            }
            set
            {
                this.meritveField = value;
                this.RaisePropertyChanged("meritve");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 6)]
        public string msg
        {
            get
            {
                return this.msgField;
            }
            set
            {
                this.msgField = value;
                this.RaisePropertyChanged("msg");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("narocilnice", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true, Order = 7)]
        public dokument[] narocilnice
        {
            get
            {
                return this.narocilniceField;
            }
            set
            {
                this.narocilniceField = value;
                this.RaisePropertyChanged("narocilnice");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("pooblastila", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true, Order = 8)]
        public dokument[] pooblastila
        {
            get
            {
                return this.pooblastilaField;
            }
            set
            {
                this.pooblastilaField = value;
                this.RaisePropertyChanged("pooblastila");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 9)]
        public int rc
        {
            get
            {
                return this.rcField;
            }
            set
            {
                this.rcField = value;
                this.RaisePropertyChanged("rc");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool rcSpecified
        {
            get
            {
                return this.rcFieldSpecified;
            }
            set
            {
                this.rcFieldSpecified = value;
                this.RaisePropertyChanged("rcSpecified");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 10)]
        public int sifraDobavitelja
        {
            get
            {
                return this.sifraDobaviteljaField;
            }
            set
            {
                this.sifraDobaviteljaField = value;
                this.RaisePropertyChanged("sifraDobavitelja");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool sifraDobaviteljaSpecified
        {
            get
            {
                return this.sifraDobaviteljaFieldSpecified;
            }
            set
            {
                this.sifraDobaviteljaFieldSpecified = value;
                this.RaisePropertyChanged("sifraDobaviteljaSpecified");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 11)]
        public int smm
        {
            get
            {
                return this.smmField;
            }
            set
            {
                this.smmField = value;
                this.RaisePropertyChanged("smm");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 12)]
        public string statusEvidence
        {
            get
            {
                return this.statusEvidenceField;
            }
            set
            {
                this.statusEvidenceField = value;
                this.RaisePropertyChanged("statusEvidence");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 13)]
        public string vrstaStoritve
        {
            get
            {
                return this.vrstaStoritveField;
            }
            set
            {
                this.vrstaStoritveField = value;
                this.RaisePropertyChanged("vrstaStoritve");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://servis.EvidencaMMDobaviteljWS.informatika.si/")]
    public partial class dokument : object, System.ComponentModel.INotifyPropertyChanged
    {

        private string imeField;

        private string tipField;

        private string vrstaDokumentaField;

        private byte[] vsebinaField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public string ime
        {
            get
            {
                return this.imeField;
            }
            set
            {
                this.imeField = value;
                this.RaisePropertyChanged("ime");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public string tip
        {
            get
            {
                return this.tipField;
            }
            set
            {
                this.tipField = value;
                this.RaisePropertyChanged("tip");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
        public string vrstaDokumenta
        {
            get
            {
                return this.vrstaDokumentaField;
            }
            set
            {
                this.vrstaDokumentaField = value;
                this.RaisePropertyChanged("vrstaDokumenta");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "base64Binary", Order = 3)]
        public byte[] vsebina
        {
            get
            {
                return this.vsebinaField;
            }
            set
            {
                this.vsebinaField = value;
                this.RaisePropertyChanged("vsebina");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://servis.EvidencaMMDobaviteljWS.informatika.si/")]
    public partial class oddajEvidencoZahtevek : object, System.ComponentModel.INotifyPropertyChanged
    {

        private short disField;

        private bool disFieldSpecified;

        private int obdobjeMeritevField;

        private bool obdobjeMeritevFieldSpecified;

        private int smmField;

        private bool smmFieldSpecified;

        private bool zahtevamMerilnePodatkeField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public short dis
        {
            get
            {
                return this.disField;
            }
            set
            {
                this.disField = value;
                this.RaisePropertyChanged("dis");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool disSpecified
        {
            get
            {
                return this.disFieldSpecified;
            }
            set
            {
                this.disFieldSpecified = value;
                this.RaisePropertyChanged("disSpecified");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public int obdobjeMeritev
        {
            get
            {
                return this.obdobjeMeritevField;
            }
            set
            {
                this.obdobjeMeritevField = value;
                this.RaisePropertyChanged("obdobjeMeritev");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool obdobjeMeritevSpecified
        {
            get
            {
                return this.obdobjeMeritevFieldSpecified;
            }
            set
            {
                this.obdobjeMeritevFieldSpecified = value;
                this.RaisePropertyChanged("obdobjeMeritevSpecified");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
        public int smm
        {
            get
            {
                return this.smmField;
            }
            set
            {
                this.smmField = value;
                this.RaisePropertyChanged("smm");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool smmSpecified
        {
            get
            {
                return this.smmFieldSpecified;
            }
            set
            {
                this.smmFieldSpecified = value;
                this.RaisePropertyChanged("smmSpecified");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 3)]
        public bool zahtevamMerilnePodatke
        {
            get
            {
                return this.zahtevamMerilnePodatkeField;
            }
            set
            {
                this.zahtevamMerilnePodatkeField = value;
                this.RaisePropertyChanged("zahtevamMerilnePodatke");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://servis.EvidencaMMDobaviteljWS.informatika.si/")]
    public partial class seznamEvidencOdgovor : object, System.ComponentModel.INotifyPropertyChanged
    {

        private string msgField;

        private int rcField;

        private evidencaOdgovor[] seznamEvidencField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public string msg
        {
            get
            {
                return this.msgField;
            }
            set
            {
                this.msgField = value;
                this.RaisePropertyChanged("msg");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public int rc
        {
            get
            {
                return this.rcField;
            }
            set
            {
                this.rcField = value;
                this.RaisePropertyChanged("rc");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("seznamEvidenc", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true, Order = 2)]
        public evidencaOdgovor[] seznamEvidenc
        {
            get
            {
                return this.seznamEvidencField;
            }
            set
            {
                this.seznamEvidencField = value;
                this.RaisePropertyChanged("seznamEvidenc");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://servis.EvidencaMMDobaviteljWS.informatika.si/")]
    public partial class seznamEvidencZahtevek : object, System.ComponentModel.INotifyPropertyChanged
    {

        private System.DateTime datumDoField;

        private bool datumDoFieldSpecified;

        private System.DateTime datumOdField;

        private bool datumOdFieldSpecified;

        private string statusEvidencField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public System.DateTime datumDo
        {
            get
            {
                return this.datumDoField;
            }
            set
            {
                this.datumDoField = value;
                this.RaisePropertyChanged("datumDo");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool datumDoSpecified
        {
            get
            {
                return this.datumDoFieldSpecified;
            }
            set
            {
                this.datumDoFieldSpecified = value;
                this.RaisePropertyChanged("datumDoSpecified");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public System.DateTime datumOd
        {
            get
            {
                return this.datumOdField;
            }
            set
            {
                this.datumOdField = value;
                this.RaisePropertyChanged("datumOd");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool datumOdSpecified
        {
            get
            {
                return this.datumOdFieldSpecified;
            }
            set
            {
                this.datumOdFieldSpecified = value;
                this.RaisePropertyChanged("datumOdSpecified");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
        public string statusEvidenc
        {
            get
            {
                return this.statusEvidencField;
            }
            set
            {
                this.statusEvidencField = value;
                this.RaisePropertyChanged("statusEvidenc");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "najdiEvidenco", WrapperNamespace = "http://servis.EvidencaMMDobaviteljWS.informatika.si/", IsWrapped = true)]
    public partial class najdiEvidencoRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://servis.EvidencaMMDobaviteljWS.informatika.si/", Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int evidencaId;

        public najdiEvidencoRequest()
        {
        }

        public najdiEvidencoRequest(int evidencaId)
        {
            this.evidencaId = evidencaId;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "najdiEvidencoResponse", WrapperNamespace = "http://servis.EvidencaMMDobaviteljWS.informatika.si/", IsWrapped = true)]
    public partial class najdiEvidencoResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://servis.EvidencaMMDobaviteljWS.informatika.si/", Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public KomunikatorEGP.ws_Inf_EvidencaMM.evidencaOdgovor @return;

        public najdiEvidencoResponse()
        {
        }

        public najdiEvidencoResponse(KomunikatorEGP.ws_Inf_EvidencaMM.evidencaOdgovor @return)
        {
            this.@return = @return;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "najdiEvidencoPodrobnosti", WrapperNamespace = "http://servis.EvidencaMMDobaviteljWS.informatika.si/", IsWrapped = true)]
    public partial class najdiEvidencoPodrobnostiRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://servis.EvidencaMMDobaviteljWS.informatika.si/", Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int evidencaId;

        public najdiEvidencoPodrobnostiRequest()
        {
        }

        public najdiEvidencoPodrobnostiRequest(int evidencaId)
        {
            this.evidencaId = evidencaId;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "najdiEvidencoPodrobnostiResponse", WrapperNamespace = "http://servis.EvidencaMMDobaviteljWS.informatika.si/", IsWrapped = true)]
    public partial class najdiEvidencoPodrobnostiResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://servis.EvidencaMMDobaviteljWS.informatika.si/", Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public KomunikatorEGP.ws_Inf_EvidencaMM.evidencaOdgovor @return;

        public najdiEvidencoPodrobnostiResponse()
        {
        }

        public najdiEvidencoPodrobnostiResponse(KomunikatorEGP.ws_Inf_EvidencaMM.evidencaOdgovor @return)
        {
            this.@return = @return;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "najdiSeznamEvidenc", WrapperNamespace = "http://servis.EvidencaMMDobaviteljWS.informatika.si/", IsWrapped = true)]
    public partial class najdiSeznamEvidencRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://servis.EvidencaMMDobaviteljWS.informatika.si/", Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public KomunikatorEGP.ws_Inf_EvidencaMM.seznamEvidencZahtevek arg0;

        public najdiSeznamEvidencRequest()
        {
        }

        public najdiSeznamEvidencRequest(KomunikatorEGP.ws_Inf_EvidencaMM.seznamEvidencZahtevek arg0)
        {
            this.arg0 = arg0;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "najdiSeznamEvidencResponse", WrapperNamespace = "http://servis.EvidencaMMDobaviteljWS.informatika.si/", IsWrapped = true)]
    public partial class najdiSeznamEvidencResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://servis.EvidencaMMDobaviteljWS.informatika.si/", Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public KomunikatorEGP.ws_Inf_EvidencaMM.seznamEvidencOdgovor @return;

        public najdiSeznamEvidencResponse()
        {
        }

        public najdiSeznamEvidencResponse(KomunikatorEGP.ws_Inf_EvidencaMM.seznamEvidencOdgovor @return)
        {
            this.@return = @return;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "oddajEvidenco", WrapperNamespace = "http://servis.EvidencaMMDobaviteljWS.informatika.si/", IsWrapped = true)]
    public partial class oddajEvidencoRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://servis.EvidencaMMDobaviteljWS.informatika.si/", Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public KomunikatorEGP.ws_Inf_EvidencaMM.oddajEvidencoZahtevek zahtevek;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://servis.EvidencaMMDobaviteljWS.informatika.si/", Order = 1)]
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public KomunikatorEGP.ws_Inf_EvidencaMM.dokument pooblastilo;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://servis.EvidencaMMDobaviteljWS.informatika.si/", Order = 2)]
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public KomunikatorEGP.ws_Inf_EvidencaMM.dokument narocilnica;

        public oddajEvidencoRequest()
        {
        }

        public oddajEvidencoRequest(KomunikatorEGP.ws_Inf_EvidencaMM.oddajEvidencoZahtevek zahtevek, KomunikatorEGP.ws_Inf_EvidencaMM.dokument pooblastilo, KomunikatorEGP.ws_Inf_EvidencaMM.dokument narocilnica)
        {
            this.zahtevek = zahtevek;
            this.pooblastilo = pooblastilo;
            this.narocilnica = narocilnica;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "oddajEvidencoResponse", WrapperNamespace = "http://servis.EvidencaMMDobaviteljWS.informatika.si/", IsWrapped = true)]
    public partial class oddajEvidencoResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://servis.EvidencaMMDobaviteljWS.informatika.si/", Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public KomunikatorEGP.ws_Inf_EvidencaMM.evidencaOdgovor @return;

        public oddajEvidencoResponse()
        {
        }

        public oddajEvidencoResponse(KomunikatorEGP.ws_Inf_EvidencaMM.evidencaOdgovor @return)
        {
            this.@return = @return;
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface EvidencaMMDobaviteljWSChannel : KomunikatorEGP.ws_Inf_EvidencaMM.EvidencaMMDobaviteljWS, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EvidencaMMDobaviteljWSClient : System.ServiceModel.ClientBase<KomunikatorEGP.ws_Inf_EvidencaMM.EvidencaMMDobaviteljWS>, KomunikatorEGP.ws_Inf_EvidencaMM.EvidencaMMDobaviteljWS
    {

        public EvidencaMMDobaviteljWSClient()
        {
        }

        public EvidencaMMDobaviteljWSClient(string endpointConfigurationName) :
            base(endpointConfigurationName)
        {
        }

        public EvidencaMMDobaviteljWSClient(string endpointConfigurationName, string remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
        {
        }

        public EvidencaMMDobaviteljWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
        {
        }

        public EvidencaMMDobaviteljWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
            base(binding, remoteAddress)
        {
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        KomunikatorEGP.ws_Inf_EvidencaMM.najdiEvidencoResponse KomunikatorEGP.ws_Inf_EvidencaMM.EvidencaMMDobaviteljWS.najdiEvidenco(KomunikatorEGP.ws_Inf_EvidencaMM.najdiEvidencoRequest request)
        {
            return base.Channel.najdiEvidenco(request);
        }

        public KomunikatorEGP.ws_Inf_EvidencaMM.evidencaOdgovor najdiEvidenco(int evidencaId)
        {
            KomunikatorEGP.ws_Inf_EvidencaMM.najdiEvidencoRequest inValue = new KomunikatorEGP.ws_Inf_EvidencaMM.najdiEvidencoRequest();
            inValue.evidencaId = evidencaId;
            KomunikatorEGP.ws_Inf_EvidencaMM.najdiEvidencoResponse retVal = ((KomunikatorEGP.ws_Inf_EvidencaMM.EvidencaMMDobaviteljWS)(this)).najdiEvidenco(inValue);
            return retVal.@return;
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        KomunikatorEGP.ws_Inf_EvidencaMM.najdiEvidencoPodrobnostiResponse KomunikatorEGP.ws_Inf_EvidencaMM.EvidencaMMDobaviteljWS.najdiEvidencoPodrobnosti(KomunikatorEGP.ws_Inf_EvidencaMM.najdiEvidencoPodrobnostiRequest request)
        {
            return base.Channel.najdiEvidencoPodrobnosti(request);
        }

        public KomunikatorEGP.ws_Inf_EvidencaMM.evidencaOdgovor najdiEvidencoPodrobnosti(int evidencaId)
        {
            KomunikatorEGP.ws_Inf_EvidencaMM.najdiEvidencoPodrobnostiRequest inValue = new KomunikatorEGP.ws_Inf_EvidencaMM.najdiEvidencoPodrobnostiRequest();
            inValue.evidencaId = evidencaId;
            KomunikatorEGP.ws_Inf_EvidencaMM.najdiEvidencoPodrobnostiResponse retVal = ((KomunikatorEGP.ws_Inf_EvidencaMM.EvidencaMMDobaviteljWS)(this)).najdiEvidencoPodrobnosti(inValue);
            return retVal.@return;
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        KomunikatorEGP.ws_Inf_EvidencaMM.najdiSeznamEvidencResponse KomunikatorEGP.ws_Inf_EvidencaMM.EvidencaMMDobaviteljWS.najdiSeznamEvidenc(KomunikatorEGP.ws_Inf_EvidencaMM.najdiSeznamEvidencRequest request)
        {
            return base.Channel.najdiSeznamEvidenc(request);
        }

        public KomunikatorEGP.ws_Inf_EvidencaMM.seznamEvidencOdgovor najdiSeznamEvidenc(KomunikatorEGP.ws_Inf_EvidencaMM.seznamEvidencZahtevek arg0)
        {
            KomunikatorEGP.ws_Inf_EvidencaMM.najdiSeznamEvidencRequest inValue = new KomunikatorEGP.ws_Inf_EvidencaMM.najdiSeznamEvidencRequest();
            inValue.arg0 = arg0;
            KomunikatorEGP.ws_Inf_EvidencaMM.najdiSeznamEvidencResponse retVal = ((KomunikatorEGP.ws_Inf_EvidencaMM.EvidencaMMDobaviteljWS)(this)).najdiSeznamEvidenc(inValue);
            return retVal.@return;
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        KomunikatorEGP.ws_Inf_EvidencaMM.oddajEvidencoResponse KomunikatorEGP.ws_Inf_EvidencaMM.EvidencaMMDobaviteljWS.oddajEvidenco(KomunikatorEGP.ws_Inf_EvidencaMM.oddajEvidencoRequest request)
        {
            return base.Channel.oddajEvidenco(request);
        }

        public KomunikatorEGP.ws_Inf_EvidencaMM.evidencaOdgovor oddajEvidenco(KomunikatorEGP.ws_Inf_EvidencaMM.oddajEvidencoZahtevek zahtevek, KomunikatorEGP.ws_Inf_EvidencaMM.dokument pooblastilo, KomunikatorEGP.ws_Inf_EvidencaMM.dokument narocilnica)
        {
            KomunikatorEGP.ws_Inf_EvidencaMM.oddajEvidencoRequest inValue = new KomunikatorEGP.ws_Inf_EvidencaMM.oddajEvidencoRequest();
            inValue.zahtevek = zahtevek;
            inValue.pooblastilo = pooblastilo;
            inValue.narocilnica = narocilnica;
            KomunikatorEGP.ws_Inf_EvidencaMM.oddajEvidencoResponse retVal = ((KomunikatorEGP.ws_Inf_EvidencaMM.EvidencaMMDobaviteljWS)(this)).oddajEvidenco(inValue);
            return retVal.@return;
        }
    }
}
