//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GemaLogicLib.GemaLogicServiceClient {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://generalynx.com/gema/webservice/bulkdataretriever", ConfigurationName="GemaLogicServiceClient.DataRetrieverBulkEndpoint")]
    public interface DataRetrieverBulkEndpoint {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(readLastValue))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getAllDataSourcesInGroup))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(readAggregatedDataList))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(readData))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getDataSourceInGroupResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getDataSourceInGroup))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        GemaLogicLib.GemaLogicServiceClient.getDataSourceInGroupResponse1 getDataSourceInGroup(GemaLogicLib.GemaLogicServiceClient.getDataSourceInGroup1 request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(readLastValue))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getAllDataSourcesInGroup))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(readAggregatedDataList))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(readData))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getDataSourceInGroupResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getDataSourceInGroup))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        GemaLogicLib.GemaLogicServiceClient.readDataResponse readData(GemaLogicLib.GemaLogicServiceClient.readData1 request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(readLastValue))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getAllDataSourcesInGroup))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(readAggregatedDataList))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(readData))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getDataSourceInGroupResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getDataSourceInGroup))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        GemaLogicLib.GemaLogicServiceClient.readAggregatedDataListResponse readAggregatedDataList(GemaLogicLib.GemaLogicServiceClient.readAggregatedDataList1 request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(readLastValue))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getAllDataSourcesInGroup))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(readAggregatedDataList))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(readData))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getDataSourceInGroupResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getDataSourceInGroup))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        GemaLogicLib.GemaLogicServiceClient.getAllDataSourcesInGroupResponse getAllDataSourcesInGroup(GemaLogicLib.GemaLogicServiceClient.getAllDataSourcesInGroup1 request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(readLastValue))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getAllDataSourcesInGroup))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(readAggregatedDataList))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(readData))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getDataSourceInGroupResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getDataSourceInGroup))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        GemaLogicLib.GemaLogicServiceClient.readLastValueResponse readLastValue(GemaLogicLib.GemaLogicServiceClient.readLastValue1 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://generalynx.com/gema/webservice/bulkdataretriever")]
    public partial class dataSourceQuery : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string dataSourceExternalIdentField;
        
        private string dataSourceGroupExternalIdentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string dataSourceExternalIdent {
            get {
                return this.dataSourceExternalIdentField;
            }
            set {
                this.dataSourceExternalIdentField = value;
                this.RaisePropertyChanged("dataSourceExternalIdent");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string dataSourceGroupExternalIdent {
            get {
                return this.dataSourceGroupExternalIdentField;
            }
            set {
                this.dataSourceGroupExternalIdentField = value;
                this.RaisePropertyChanged("dataSourceGroupExternalIdent");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://generalynx.com/gema/webservice/bulkdataretriever")]
    public partial class readLastValue : object, System.ComponentModel.INotifyPropertyChanged {
        
        private gListQuery arg0Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public gListQuery arg0 {
            get {
                return this.arg0Field;
            }
            set {
                this.arg0Field = value;
                this.RaisePropertyChanged("arg0");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://generalynx.com/gema/webservice/bulkdataretriever")]
    public partial class gListQuery : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Nullable<long>[] dataSourceIdsField;
        
        private System.DateTime fromDField;
        
        private bool fromDFieldSpecified;
        
        private timeInterval timeIntervalField;
        
        private bool timeIntervalFieldSpecified;
        
        private System.DateTime toDField;
        
        private bool toDFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("dataSourceIds", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public System.Nullable<long>[] dataSourceIds {
            get {
                return this.dataSourceIdsField;
            }
            set {
                this.dataSourceIdsField = value;
                this.RaisePropertyChanged("dataSourceIds");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public System.DateTime fromD {
            get {
                return this.fromDField;
            }
            set {
                this.fromDField = value;
                this.RaisePropertyChanged("fromD");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fromDSpecified {
            get {
                return this.fromDFieldSpecified;
            }
            set {
                this.fromDFieldSpecified = value;
                this.RaisePropertyChanged("fromDSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public timeInterval timeInterval {
            get {
                return this.timeIntervalField;
            }
            set {
                this.timeIntervalField = value;
                this.RaisePropertyChanged("timeInterval");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool timeIntervalSpecified {
            get {
                return this.timeIntervalFieldSpecified;
            }
            set {
                this.timeIntervalFieldSpecified = value;
                this.RaisePropertyChanged("timeIntervalSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public System.DateTime toD {
            get {
                return this.toDField;
            }
            set {
                this.toDField = value;
                this.RaisePropertyChanged("toD");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool toDSpecified {
            get {
                return this.toDFieldSpecified;
            }
            set {
                this.toDFieldSpecified = value;
                this.RaisePropertyChanged("toDSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://generalynx.com/gema/webservice/bulkdataretriever")]
    public enum timeInterval {
        
        /// <remarks/>
        n,
        
        /// <remarks/>
        s,
        
        /// <remarks/>
        e,
        
        /// <remarks/>
        m,
        
        /// <remarks/>
        v,
        
        /// <remarks/>
        f,
        
        /// <remarks/>
        t,
        
        /// <remarks/>
        q,
        
        /// <remarks/>
        V,
        
        /// <remarks/>
        h,
        
        /// <remarks/>
        H,
        
        /// <remarks/>
        T,
        
        /// <remarks/>
        S,
        
        /// <remarks/>
        E,
        
        /// <remarks/>
        W,
        
        /// <remarks/>
        d,
        
        /// <remarks/>
        w,
        
        /// <remarks/>
        l,
        
        /// <remarks/>
        M,
        
        /// <remarks/>
        Q,
        
        /// <remarks/>
        y,
        
        /// <remarks/>
        X,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://generalynx.com/gema/webservice/bulkdataretriever")]
    public partial class dataSourceGroupQuery : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string dataSourceGroupExternalIdentField;
        
        private dataSourceGroupUsageType dataSourceUsageTypeField;
        
        private bool dataSourceUsageTypeFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string dataSourceGroupExternalIdent {
            get {
                return this.dataSourceGroupExternalIdentField;
            }
            set {
                this.dataSourceGroupExternalIdentField = value;
                this.RaisePropertyChanged("dataSourceGroupExternalIdent");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public dataSourceGroupUsageType dataSourceUsageType {
            get {
                return this.dataSourceUsageTypeField;
            }
            set {
                this.dataSourceUsageTypeField = value;
                this.RaisePropertyChanged("dataSourceUsageType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dataSourceUsageTypeSpecified {
            get {
                return this.dataSourceUsageTypeFieldSpecified;
            }
            set {
                this.dataSourceUsageTypeFieldSpecified = value;
                this.RaisePropertyChanged("dataSourceUsageTypeSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://generalynx.com/gema/webservice/bulkdataretriever")]
    public enum dataSourceGroupUsageType {
        
        /// <remarks/>
        common,
        
        /// <remarks/>
        XMLDP,
        
        /// <remarks/>
        Export,
        
        /// <remarks/>
        ElConsm,
        
        /// <remarks/>
        WS,
        
        /// <remarks/>
        GasNetC,
        
        /// <remarks/>
        BillDat,
        
        /// <remarks/>
        BalAcc,
        
        /// <remarks/>
        gasFor,
        
        /// <remarks/>
        GasInvI,
        
        /// <remarks/>
        FrcAlrm,
        
        /// <remarks/>
        WthWgh,
        
        /// <remarks/>
        NomAcc,
        
        /// <remarks/>
        HeatSea,
        
        /// <remarks/>
        LocGrp,
        
        /// <remarks/>
        Correct,
        
        /// <remarks/>
        GDAClnt,
        
        /// <remarks/>
        CGD,
        
        /// <remarks/>
        MapTrCC,
        
        /// <remarks/>
        eleInvM,
        
        /// <remarks/>
        aggEle,
        
        /// <remarks/>
        aggElTf,
        
        /// <remarks/>
        epop,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://generalynx.com/gema/webservice/bulkdataretriever")]
    public partial class getAllDataSourcesInGroup : object, System.ComponentModel.INotifyPropertyChanged {
        
        private dataSourceGroupQuery arg0Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public dataSourceGroupQuery arg0 {
            get {
                return this.arg0Field;
            }
            set {
                this.arg0Field = value;
                this.RaisePropertyChanged("arg0");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://generalynx.com/gema/webservice/bulkdataretriever")]
    public partial class mValueArray : object, System.ComponentModel.INotifyPropertyChanged {
        
        private mValue[] itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public mValue[] item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
                this.RaisePropertyChanged("item");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://generalynx.com/gema/webservice/bulkdataretriever")]
    public partial class mValue : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long dataSourceIdField;
        
        private bool dataSourceIdFieldSpecified;
        
        private object result1Field;
        
        private object result2Field;
        
        private object result3Field;
        
        private object result4Field;
        
        private object result5Field;
        
        private object result6Field;
        
        private object result7Field;
        
        private System.DateTime timeField;
        
        private bool timeFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long dataSourceId {
            get {
                return this.dataSourceIdField;
            }
            set {
                this.dataSourceIdField = value;
                this.RaisePropertyChanged("dataSourceId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dataSourceIdSpecified {
            get {
                return this.dataSourceIdFieldSpecified;
            }
            set {
                this.dataSourceIdFieldSpecified = value;
                this.RaisePropertyChanged("dataSourceIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public object result1 {
            get {
                return this.result1Field;
            }
            set {
                this.result1Field = value;
                this.RaisePropertyChanged("result1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public object result2 {
            get {
                return this.result2Field;
            }
            set {
                this.result2Field = value;
                this.RaisePropertyChanged("result2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public object result3 {
            get {
                return this.result3Field;
            }
            set {
                this.result3Field = value;
                this.RaisePropertyChanged("result3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public object result4 {
            get {
                return this.result4Field;
            }
            set {
                this.result4Field = value;
                this.RaisePropertyChanged("result4");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public object result5 {
            get {
                return this.result5Field;
            }
            set {
                this.result5Field = value;
                this.RaisePropertyChanged("result5");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public object result6 {
            get {
                return this.result6Field;
            }
            set {
                this.result6Field = value;
                this.RaisePropertyChanged("result6");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public object result7 {
            get {
                return this.result7Field;
            }
            set {
                this.result7Field = value;
                this.RaisePropertyChanged("result7");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public System.DateTime time {
            get {
                return this.timeField;
            }
            set {
                this.timeField = value;
                this.RaisePropertyChanged("time");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool timeSpecified {
            get {
                return this.timeFieldSpecified;
            }
            set {
                this.timeFieldSpecified = value;
                this.RaisePropertyChanged("timeSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://generalynx.com/gema/webservice/bulkdataretriever")]
    public partial class readAggregatedDataList : object, System.ComponentModel.INotifyPropertyChanged {
        
        private gListQuery arg0Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public gListQuery arg0 {
            get {
                return this.arg0Field;
            }
            set {
                this.arg0Field = value;
                this.RaisePropertyChanged("arg0");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://generalynx.com/gema/webservice/bulkdataretriever")]
    public partial class gQuery : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long dataSourceIdField;
        
        private bool dataSourceIdFieldSpecified;
        
        private System.DateTime fromDField;
        
        private bool fromDFieldSpecified;
        
        private timeInterval timeIntervalField;
        
        private bool timeIntervalFieldSpecified;
        
        private System.DateTime toDField;
        
        private bool toDFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long dataSourceId {
            get {
                return this.dataSourceIdField;
            }
            set {
                this.dataSourceIdField = value;
                this.RaisePropertyChanged("dataSourceId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dataSourceIdSpecified {
            get {
                return this.dataSourceIdFieldSpecified;
            }
            set {
                this.dataSourceIdFieldSpecified = value;
                this.RaisePropertyChanged("dataSourceIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public System.DateTime fromD {
            get {
                return this.fromDField;
            }
            set {
                this.fromDField = value;
                this.RaisePropertyChanged("fromD");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fromDSpecified {
            get {
                return this.fromDFieldSpecified;
            }
            set {
                this.fromDFieldSpecified = value;
                this.RaisePropertyChanged("fromDSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public timeInterval timeInterval {
            get {
                return this.timeIntervalField;
            }
            set {
                this.timeIntervalField = value;
                this.RaisePropertyChanged("timeInterval");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool timeIntervalSpecified {
            get {
                return this.timeIntervalFieldSpecified;
            }
            set {
                this.timeIntervalFieldSpecified = value;
                this.RaisePropertyChanged("timeIntervalSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public System.DateTime toD {
            get {
                return this.toDField;
            }
            set {
                this.toDField = value;
                this.RaisePropertyChanged("toD");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool toDSpecified {
            get {
                return this.toDFieldSpecified;
            }
            set {
                this.toDFieldSpecified = value;
                this.RaisePropertyChanged("toDSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://generalynx.com/gema/webservice/bulkdataretriever")]
    public partial class readData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private gQuery arg0Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public gQuery arg0 {
            get {
                return this.arg0Field;
            }
            set {
                this.arg0Field = value;
                this.RaisePropertyChanged("arg0");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://generalynx.com/gema/webservice/bulkdataretriever")]
    public partial class getDataSourceInGroupResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private dataSource returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public dataSource @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
                this.RaisePropertyChanged("return");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://generalynx.com/gema/webservice/dataretriever")]
    public partial class dataSource : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string externalIdentField;
        
        private long idField;
        
        private bool idFieldSpecified;
        
        private tValue lastValueField;
        
        private string nameField;
        
        private long productIdField;
        
        private bool productIdFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string externalIdent {
            get {
                return this.externalIdentField;
            }
            set {
                this.externalIdentField = value;
                this.RaisePropertyChanged("externalIdent");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
                this.RaisePropertyChanged("idSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public tValue lastValue {
            get {
                return this.lastValueField;
            }
            set {
                this.lastValueField = value;
                this.RaisePropertyChanged("lastValue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public long productId {
            get {
                return this.productIdField;
            }
            set {
                this.productIdField = value;
                this.RaisePropertyChanged("productId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool productIdSpecified {
            get {
                return this.productIdFieldSpecified;
            }
            set {
                this.productIdFieldSpecified = value;
                this.RaisePropertyChanged("productIdSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://generalynx.com/gema/webservice/bulkdataretriever")]
    public partial class tValue : object, System.ComponentModel.INotifyPropertyChanged {
        
        private object result1Field;
        
        private object result2Field;
        
        private object result3Field;
        
        private object result4Field;
        
        private object result5Field;
        
        private object result6Field;
        
        private object result7Field;
        
        private System.DateTime timeField;
        
        private bool timeFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public object result1 {
            get {
                return this.result1Field;
            }
            set {
                this.result1Field = value;
                this.RaisePropertyChanged("result1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public object result2 {
            get {
                return this.result2Field;
            }
            set {
                this.result2Field = value;
                this.RaisePropertyChanged("result2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public object result3 {
            get {
                return this.result3Field;
            }
            set {
                this.result3Field = value;
                this.RaisePropertyChanged("result3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public object result4 {
            get {
                return this.result4Field;
            }
            set {
                this.result4Field = value;
                this.RaisePropertyChanged("result4");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public object result5 {
            get {
                return this.result5Field;
            }
            set {
                this.result5Field = value;
                this.RaisePropertyChanged("result5");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public object result6 {
            get {
                return this.result6Field;
            }
            set {
                this.result6Field = value;
                this.RaisePropertyChanged("result6");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public object result7 {
            get {
                return this.result7Field;
            }
            set {
                this.result7Field = value;
                this.RaisePropertyChanged("result7");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public System.DateTime time {
            get {
                return this.timeField;
            }
            set {
                this.timeField = value;
                this.RaisePropertyChanged("time");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool timeSpecified {
            get {
                return this.timeFieldSpecified;
            }
            set {
                this.timeFieldSpecified = value;
                this.RaisePropertyChanged("timeSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://generalynx.com/gema/webservice/bulkdataretriever")]
    public partial class getDataSourceInGroup : object, System.ComponentModel.INotifyPropertyChanged {
        
        private dataSourceQuery arg0Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public dataSourceQuery arg0 {
            get {
                return this.arg0Field;
            }
            set {
                this.arg0Field = value;
                this.RaisePropertyChanged("arg0");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getDataSourceInGroup", WrapperNamespace="http://generalynx.com/gema/webservice/bulkdataretriever", IsWrapped=true)]
    public partial class getDataSourceInGroup1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://generalynx.com/gema/webservice/bulkdataretriever", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GemaLogicLib.GemaLogicServiceClient.dataSourceQuery arg0;
        
        public getDataSourceInGroup1() {
        }
        
        public getDataSourceInGroup1(GemaLogicLib.GemaLogicServiceClient.dataSourceQuery arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getDataSourceInGroupResponse", WrapperNamespace="http://generalynx.com/gema/webservice/bulkdataretriever", IsWrapped=true)]
    public partial class getDataSourceInGroupResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://generalynx.com/gema/webservice/bulkdataretriever", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GemaLogicLib.GemaLogicServiceClient.dataSource @return;
        
        public getDataSourceInGroupResponse1() {
        }
        
        public getDataSourceInGroupResponse1(GemaLogicLib.GemaLogicServiceClient.dataSource @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="readData", WrapperNamespace="http://generalynx.com/gema/webservice/bulkdataretriever", IsWrapped=true)]
    public partial class readData1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://generalynx.com/gema/webservice/bulkdataretriever", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GemaLogicLib.GemaLogicServiceClient.gQuery arg0;
        
        public readData1() {
        }
        
        public readData1(GemaLogicLib.GemaLogicServiceClient.gQuery arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="readDataResponse", WrapperNamespace="http://generalynx.com/gema/webservice/bulkdataretriever", IsWrapped=true)]
    public partial class readDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://generalynx.com/gema/webservice/bulkdataretriever", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GemaLogicLib.GemaLogicServiceClient.tValue[] @return;
        
        public readDataResponse() {
        }
        
        public readDataResponse(GemaLogicLib.GemaLogicServiceClient.tValue[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="readAggregatedDataList", WrapperNamespace="http://generalynx.com/gema/webservice/bulkdataretriever", IsWrapped=true)]
    public partial class readAggregatedDataList1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://generalynx.com/gema/webservice/bulkdataretriever", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GemaLogicLib.GemaLogicServiceClient.gListQuery arg0;
        
        public readAggregatedDataList1() {
        }
        
        public readAggregatedDataList1(GemaLogicLib.GemaLogicServiceClient.gListQuery arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="readAggregatedDataListResponse", WrapperNamespace="http://generalynx.com/gema/webservice/bulkdataretriever", IsWrapped=true)]
    public partial class readAggregatedDataListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://generalynx.com/gema/webservice/bulkdataretriever", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GemaLogicLib.GemaLogicServiceClient.mValueArray[] @return;
        
        public readAggregatedDataListResponse() {
        }
        
        public readAggregatedDataListResponse(GemaLogicLib.GemaLogicServiceClient.mValueArray[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAllDataSourcesInGroup", WrapperNamespace="http://generalynx.com/gema/webservice/bulkdataretriever", IsWrapped=true)]
    public partial class getAllDataSourcesInGroup1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://generalynx.com/gema/webservice/bulkdataretriever", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GemaLogicLib.GemaLogicServiceClient.dataSourceGroupQuery arg0;
        
        public getAllDataSourcesInGroup1() {
        }
        
        public getAllDataSourcesInGroup1(GemaLogicLib.GemaLogicServiceClient.dataSourceGroupQuery arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAllDataSourcesInGroupResponse", WrapperNamespace="http://generalynx.com/gema/webservice/bulkdataretriever", IsWrapped=true)]
    public partial class getAllDataSourcesInGroupResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://generalynx.com/gema/webservice/bulkdataretriever", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GemaLogicLib.GemaLogicServiceClient.dataSource[] @return;
        
        public getAllDataSourcesInGroupResponse() {
        }
        
        public getAllDataSourcesInGroupResponse(GemaLogicLib.GemaLogicServiceClient.dataSource[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="readLastValue", WrapperNamespace="http://generalynx.com/gema/webservice/bulkdataretriever", IsWrapped=true)]
    public partial class readLastValue1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://generalynx.com/gema/webservice/bulkdataretriever", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GemaLogicLib.GemaLogicServiceClient.gListQuery arg0;
        
        public readLastValue1() {
        }
        
        public readLastValue1(GemaLogicLib.GemaLogicServiceClient.gListQuery arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="readLastValueResponse", WrapperNamespace="http://generalynx.com/gema/webservice/bulkdataretriever", IsWrapped=true)]
    public partial class readLastValueResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://generalynx.com/gema/webservice/bulkdataretriever", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GemaLogicLib.GemaLogicServiceClient.mValue[] @return;
        
        public readLastValueResponse() {
        }
        
        public readLastValueResponse(GemaLogicLib.GemaLogicServiceClient.mValue[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DataRetrieverBulkEndpointChannel : GemaLogicLib.GemaLogicServiceClient.DataRetrieverBulkEndpoint, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DataRetrieverBulkEndpointClient : System.ServiceModel.ClientBase<GemaLogicLib.GemaLogicServiceClient.DataRetrieverBulkEndpoint>, GemaLogicLib.GemaLogicServiceClient.DataRetrieverBulkEndpoint {
        
        public DataRetrieverBulkEndpointClient() {
        }
        
        public DataRetrieverBulkEndpointClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DataRetrieverBulkEndpointClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataRetrieverBulkEndpointClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataRetrieverBulkEndpointClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GemaLogicLib.GemaLogicServiceClient.getDataSourceInGroupResponse1 GemaLogicLib.GemaLogicServiceClient.DataRetrieverBulkEndpoint.getDataSourceInGroup(GemaLogicLib.GemaLogicServiceClient.getDataSourceInGroup1 request) {
            return base.Channel.getDataSourceInGroup(request);
        }
        
        public GemaLogicLib.GemaLogicServiceClient.dataSource getDataSourceInGroup(GemaLogicLib.GemaLogicServiceClient.dataSourceQuery arg0) {
            GemaLogicLib.GemaLogicServiceClient.getDataSourceInGroup1 inValue = new GemaLogicLib.GemaLogicServiceClient.getDataSourceInGroup1();
            inValue.arg0 = arg0;
            GemaLogicLib.GemaLogicServiceClient.getDataSourceInGroupResponse1 retVal = ((GemaLogicLib.GemaLogicServiceClient.DataRetrieverBulkEndpoint)(this)).getDataSourceInGroup(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GemaLogicLib.GemaLogicServiceClient.readDataResponse GemaLogicLib.GemaLogicServiceClient.DataRetrieverBulkEndpoint.readData(GemaLogicLib.GemaLogicServiceClient.readData1 request) {
            return base.Channel.readData(request);
        }
        
        public GemaLogicLib.GemaLogicServiceClient.tValue[] readData(GemaLogicLib.GemaLogicServiceClient.gQuery arg0) {
            GemaLogicLib.GemaLogicServiceClient.readData1 inValue = new GemaLogicLib.GemaLogicServiceClient.readData1();
            inValue.arg0 = arg0;
            GemaLogicLib.GemaLogicServiceClient.readDataResponse retVal = ((GemaLogicLib.GemaLogicServiceClient.DataRetrieverBulkEndpoint)(this)).readData(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GemaLogicLib.GemaLogicServiceClient.readAggregatedDataListResponse GemaLogicLib.GemaLogicServiceClient.DataRetrieverBulkEndpoint.readAggregatedDataList(GemaLogicLib.GemaLogicServiceClient.readAggregatedDataList1 request) {
            return base.Channel.readAggregatedDataList(request);
        }
        
        public GemaLogicLib.GemaLogicServiceClient.mValueArray[] readAggregatedDataList(GemaLogicLib.GemaLogicServiceClient.gListQuery arg0) {
            GemaLogicLib.GemaLogicServiceClient.readAggregatedDataList1 inValue = new GemaLogicLib.GemaLogicServiceClient.readAggregatedDataList1();
            inValue.arg0 = arg0;
            GemaLogicLib.GemaLogicServiceClient.readAggregatedDataListResponse retVal = ((GemaLogicLib.GemaLogicServiceClient.DataRetrieverBulkEndpoint)(this)).readAggregatedDataList(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GemaLogicLib.GemaLogicServiceClient.getAllDataSourcesInGroupResponse GemaLogicLib.GemaLogicServiceClient.DataRetrieverBulkEndpoint.getAllDataSourcesInGroup(GemaLogicLib.GemaLogicServiceClient.getAllDataSourcesInGroup1 request) {
            return base.Channel.getAllDataSourcesInGroup(request);
        }
        
        public GemaLogicLib.GemaLogicServiceClient.dataSource[] getAllDataSourcesInGroup(GemaLogicLib.GemaLogicServiceClient.dataSourceGroupQuery arg0) {
            GemaLogicLib.GemaLogicServiceClient.getAllDataSourcesInGroup1 inValue = new GemaLogicLib.GemaLogicServiceClient.getAllDataSourcesInGroup1();
            inValue.arg0 = arg0;
            GemaLogicLib.GemaLogicServiceClient.getAllDataSourcesInGroupResponse retVal = ((GemaLogicLib.GemaLogicServiceClient.DataRetrieverBulkEndpoint)(this)).getAllDataSourcesInGroup(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GemaLogicLib.GemaLogicServiceClient.readLastValueResponse GemaLogicLib.GemaLogicServiceClient.DataRetrieverBulkEndpoint.readLastValue(GemaLogicLib.GemaLogicServiceClient.readLastValue1 request) {
            return base.Channel.readLastValue(request);
        }
        
        public GemaLogicLib.GemaLogicServiceClient.mValue[] readLastValue(GemaLogicLib.GemaLogicServiceClient.gListQuery arg0) {
            GemaLogicLib.GemaLogicServiceClient.readLastValue1 inValue = new GemaLogicLib.GemaLogicServiceClient.readLastValue1();
            inValue.arg0 = arg0;
            GemaLogicLib.GemaLogicServiceClient.readLastValueResponse retVal = ((GemaLogicLib.GemaLogicServiceClient.DataRetrieverBulkEndpoint)(this)).readLastValue(inValue);
            return retVal.@return;
        }
    }
}
