//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KomunikatorEGP.ws_Inf_StanjeStevca
{


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18054")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://servis.vnosStanjaStevcaDGWS.informatika.si/")]
    public partial class Exception : object, System.ComponentModel.INotifyPropertyChanged
    {

        private string messageField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18054")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://servis.vnosStanjaStevcaDGWS.informatika.si/")]
    public partial class stanjeStevcaResponse : object, System.ComponentModel.INotifyPropertyChanged
    {

        private System.DateTime datumStaregaOdbirkaField;

        private bool datumStaregaOdbirkaFieldSpecified;

        private short disField;

        private bool disFieldSpecified;

        private int idField;

        private bool idFieldSpecified;

        private string nazivNerilnegaMestaField;

        private int rcField;

        private bool rcFieldSpecified;

        private string sifraStevcaField;

        private int smmField;

        private bool smmFieldSpecified;

        private string sporociloField;

        private string stariETField;

        private string stariMTField;

        private string stariVTField;

        private string stodField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public System.DateTime datumStaregaOdbirka
        {
            get
            {
                return this.datumStaregaOdbirkaField;
            }
            set
            {
                this.datumStaregaOdbirkaField = value;
                this.RaisePropertyChanged("datumStaregaOdbirka");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool datumStaregaOdbirkaSpecified
        {
            get
            {
                return this.datumStaregaOdbirkaFieldSpecified;
            }
            set
            {
                this.datumStaregaOdbirkaFieldSpecified = value;
                this.RaisePropertyChanged("datumStaregaOdbirkaSpecified");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public short dis
        {
            get
            {
                return this.disField;
            }
            set
            {
                this.disField = value;
                this.RaisePropertyChanged("dis");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool disSpecified
        {
            get
            {
                return this.disFieldSpecified;
            }
            set
            {
                this.disFieldSpecified = value;
                this.RaisePropertyChanged("disSpecified");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified
        {
            get
            {
                return this.idFieldSpecified;
            }
            set
            {
                this.idFieldSpecified = value;
                this.RaisePropertyChanged("idSpecified");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 3)]
        public string nazivNerilnegaMesta
        {
            get
            {
                return this.nazivNerilnegaMestaField;
            }
            set
            {
                this.nazivNerilnegaMestaField = value;
                this.RaisePropertyChanged("nazivNerilnegaMesta");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 4)]
        public int rc
        {
            get
            {
                return this.rcField;
            }
            set
            {
                this.rcField = value;
                this.RaisePropertyChanged("rc");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool rcSpecified
        {
            get
            {
                return this.rcFieldSpecified;
            }
            set
            {
                this.rcFieldSpecified = value;
                this.RaisePropertyChanged("rcSpecified");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 5)]
        public string sifraStevca
        {
            get
            {
                return this.sifraStevcaField;
            }
            set
            {
                this.sifraStevcaField = value;
                this.RaisePropertyChanged("sifraStevca");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 6)]
        public int smm
        {
            get
            {
                return this.smmField;
            }
            set
            {
                this.smmField = value;
                this.RaisePropertyChanged("smm");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool smmSpecified
        {
            get
            {
                return this.smmFieldSpecified;
            }
            set
            {
                this.smmFieldSpecified = value;
                this.RaisePropertyChanged("smmSpecified");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 7)]
        public string sporocilo
        {
            get
            {
                return this.sporociloField;
            }
            set
            {
                this.sporociloField = value;
                this.RaisePropertyChanged("sporocilo");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 8)]
        public string stariET
        {
            get
            {
                return this.stariETField;
            }
            set
            {
                this.stariETField = value;
                this.RaisePropertyChanged("stariET");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 9)]
        public string stariMT
        {
            get
            {
                return this.stariMTField;
            }
            set
            {
                this.stariMTField = value;
                this.RaisePropertyChanged("stariMT");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 10)]
        public string stariVT
        {
            get
            {
                return this.stariVTField;
            }
            set
            {
                this.stariVTField = value;
                this.RaisePropertyChanged("stariVT");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 11)]
        public string stod
        {
            get
            {
                return this.stodField;
            }
            set
            {
                this.stodField = value;
                this.RaisePropertyChanged("stod");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18054")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://servis.vnosStanjaStevcaDGWS.informatika.si/")]
    public partial class stanjeStevcaRequest : object, System.ComponentModel.INotifyPropertyChanged
    {

        private short disField;

        private int dobaviteljField;

        private int smmField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public short dis
        {
            get
            {
                return this.disField;
            }
            set
            {
                this.disField = value;
                this.RaisePropertyChanged("dis");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public int dobavitelj
        {
            get
            {
                return this.dobaviteljField;
            }
            set
            {
                this.dobaviteljField = value;
                this.RaisePropertyChanged("dobavitelj");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
        public int smm
        {
            get
            {
                return this.smmField;
            }
            set
            {
                this.smmField = value;
                this.RaisePropertyChanged("smm");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace = "http://servis.vnosStanjaStevcaDGWS.informatika.si/", ConfigurationName = "ws_Inf_StanjeStevca.StanjeStevca")]
    public interface StanjeStevca
    {

        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action = "", ReplyAction = "*")]
        [System.ServiceModel.FaultContractAttribute(typeof(KomunikatorEGP.ws_Inf_StanjeStevca.Exception), Action = "", Name = "Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name = "return")]
        KomunikatorEGP.ws_Inf_StanjeStevca.poisciStaroStanjeResponse poisciStaroStanje(KomunikatorEGP.ws_Inf_StanjeStevca.poisciStaroStanjeRequest request);

        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action = "", ReplyAction = "*")]
        [System.ServiceModel.FaultContractAttribute(typeof(KomunikatorEGP.ws_Inf_StanjeStevca.Exception), Action = "", Name = "Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name = "return")]
        KomunikatorEGP.ws_Inf_StanjeStevca.vnesiNovoStanjeResponse vnesiNovoStanje(KomunikatorEGP.ws_Inf_StanjeStevca.vnesiNovoStanjeRequest request);

        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action = "", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name = "return")]
        KomunikatorEGP.ws_Inf_StanjeStevca.dodajKomentarResponse dodajKomentar(KomunikatorEGP.ws_Inf_StanjeStevca.dodajKomentarRequest request);

        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action = "", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name = "return")]
        KomunikatorEGP.ws_Inf_StanjeStevca.najdiZadnjiOdbirekResponse najdiZadnjiOdbirek(KomunikatorEGP.ws_Inf_StanjeStevca.najdiZadnjiOdbirekRequest request);

        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action = "", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name = "return")]
        KomunikatorEGP.ws_Inf_StanjeStevca.najdiOdbirekResponse najdiOdbirek(KomunikatorEGP.ws_Inf_StanjeStevca.najdiOdbirekRequest request);
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "poisciStaroStanje", WrapperNamespace = "http://servis.vnosStanjaStevcaDGWS.informatika.si/", IsWrapped = true)]
    public partial class poisciStaroStanjeRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://servis.vnosStanjaStevcaDGWS.informatika.si/", Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public KomunikatorEGP.ws_Inf_StanjeStevca.stanjeStevcaRequest arg0;

        public poisciStaroStanjeRequest()
        {
        }

        public poisciStaroStanjeRequest(KomunikatorEGP.ws_Inf_StanjeStevca.stanjeStevcaRequest arg0)
        {
            this.arg0 = arg0;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "poisciStaroStanjeResponse", WrapperNamespace = "http://servis.vnosStanjaStevcaDGWS.informatika.si/", IsWrapped = true)]
    public partial class poisciStaroStanjeResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://servis.vnosStanjaStevcaDGWS.informatika.si/", Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public KomunikatorEGP.ws_Inf_StanjeStevca.stanjeStevcaResponse @return;

        public poisciStaroStanjeResponse()
        {
        }

        public poisciStaroStanjeResponse(KomunikatorEGP.ws_Inf_StanjeStevca.stanjeStevcaResponse @return)
        {
            this.@return = @return;
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18054")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://servis.vnosStanjaStevcaDGWS.informatika.si/")]
    public partial class vnosStanjaRequest : object, System.ComponentModel.INotifyPropertyChanged
    {

        private System.DateTime datumNovegaOdbirkaField;

        private bool datumNovegaOdbirkaFieldSpecified;

        private short disField;

        private int dobaviteljField;

        private string noviETField;

        private string noviMTField;

        private string noviVTField;

        private int smmField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public System.DateTime datumNovegaOdbirka
        {
            get
            {
                return this.datumNovegaOdbirkaField;
            }
            set
            {
                this.datumNovegaOdbirkaField = value;
                this.RaisePropertyChanged("datumNovegaOdbirka");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool datumNovegaOdbirkaSpecified
        {
            get
            {
                return this.datumNovegaOdbirkaFieldSpecified;
            }
            set
            {
                this.datumNovegaOdbirkaFieldSpecified = value;
                this.RaisePropertyChanged("datumNovegaOdbirkaSpecified");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public short dis
        {
            get
            {
                return this.disField;
            }
            set
            {
                this.disField = value;
                this.RaisePropertyChanged("dis");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
        public int dobavitelj
        {
            get
            {
                return this.dobaviteljField;
            }
            set
            {
                this.dobaviteljField = value;
                this.RaisePropertyChanged("dobavitelj");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 3)]
        public string noviET
        {
            get
            {
                return this.noviETField;
            }
            set
            {
                this.noviETField = value;
                this.RaisePropertyChanged("noviET");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 4)]
        public string noviMT
        {
            get
            {
                return this.noviMTField;
            }
            set
            {
                this.noviMTField = value;
                this.RaisePropertyChanged("noviMT");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 5)]
        public string noviVT
        {
            get
            {
                return this.noviVTField;
            }
            set
            {
                this.noviVTField = value;
                this.RaisePropertyChanged("noviVT");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 6)]
        public int smm
        {
            get
            {
                return this.smmField;
            }
            set
            {
                this.smmField = value;
                this.RaisePropertyChanged("smm");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18054")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://servis.vnosStanjaStevcaDGWS.informatika.si/")]
    public partial class vnosStanjaResponse : object, System.ComponentModel.INotifyPropertyChanged
    {

        private short disField;

        private bool disFieldSpecified;

        private int idField;

        private bool idFieldSpecified;

        private int rcField;

        private bool rcFieldSpecified;

        private int smmField;

        private bool smmFieldSpecified;

        private string sporociloField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public short dis
        {
            get
            {
                return this.disField;
            }
            set
            {
                this.disField = value;
                this.RaisePropertyChanged("dis");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool disSpecified
        {
            get
            {
                return this.disFieldSpecified;
            }
            set
            {
                this.disFieldSpecified = value;
                this.RaisePropertyChanged("disSpecified");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified
        {
            get
            {
                return this.idFieldSpecified;
            }
            set
            {
                this.idFieldSpecified = value;
                this.RaisePropertyChanged("idSpecified");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
        public int rc
        {
            get
            {
                return this.rcField;
            }
            set
            {
                this.rcField = value;
                this.RaisePropertyChanged("rc");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool rcSpecified
        {
            get
            {
                return this.rcFieldSpecified;
            }
            set
            {
                this.rcFieldSpecified = value;
                this.RaisePropertyChanged("rcSpecified");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 3)]
        public int smm
        {
            get
            {
                return this.smmField;
            }
            set
            {
                this.smmField = value;
                this.RaisePropertyChanged("smm");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool smmSpecified
        {
            get
            {
                return this.smmFieldSpecified;
            }
            set
            {
                this.smmFieldSpecified = value;
                this.RaisePropertyChanged("smmSpecified");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 4)]
        public string sporocilo
        {
            get
            {
                return this.sporociloField;
            }
            set
            {
                this.sporociloField = value;
                this.RaisePropertyChanged("sporocilo");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "vnesiNovoStanje", WrapperNamespace = "http://servis.vnosStanjaStevcaDGWS.informatika.si/", IsWrapped = true)]
    public partial class vnesiNovoStanjeRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://servis.vnosStanjaStevcaDGWS.informatika.si/", Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public KomunikatorEGP.ws_Inf_StanjeStevca.vnosStanjaRequest arg0;

        public vnesiNovoStanjeRequest()
        {
        }

        public vnesiNovoStanjeRequest(KomunikatorEGP.ws_Inf_StanjeStevca.vnosStanjaRequest arg0)
        {
            this.arg0 = arg0;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "vnesiNovoStanjeResponse", WrapperNamespace = "http://servis.vnosStanjaStevcaDGWS.informatika.si/", IsWrapped = true)]
    public partial class vnesiNovoStanjeResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://servis.vnosStanjaStevcaDGWS.informatika.si/", Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public KomunikatorEGP.ws_Inf_StanjeStevca.vnosStanjaResponse @return;

        public vnesiNovoStanjeResponse()
        {
        }

        public vnesiNovoStanjeResponse(KomunikatorEGP.ws_Inf_StanjeStevca.vnosStanjaResponse @return)
        {
            this.@return = @return;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "dodajKomentar", WrapperNamespace = "http://servis.vnosStanjaStevcaDGWS.informatika.si/", IsWrapped = true)]
    public partial class dodajKomentarRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://servis.vnosStanjaStevcaDGWS.informatika.si/", Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idOdbirka;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://servis.vnosStanjaStevcaDGWS.informatika.si/", Order = 1)]
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string komentar;

        public dodajKomentarRequest()
        {
        }

        public dodajKomentarRequest(int idOdbirka, string komentar)
        {
            this.idOdbirka = idOdbirka;
            this.komentar = komentar;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "dodajKomentarResponse", WrapperNamespace = "http://servis.vnosStanjaStevcaDGWS.informatika.si/", IsWrapped = true)]
    public partial class dodajKomentarResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://servis.vnosStanjaStevcaDGWS.informatika.si/", Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public KomunikatorEGP.ws_Inf_StanjeStevca.vnosStanjaResponse @return;

        public dodajKomentarResponse()
        {
        }

        public dodajKomentarResponse(KomunikatorEGP.ws_Inf_StanjeStevca.vnosStanjaResponse @return)
        {
            this.@return = @return;
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18054")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://servis.vnosStanjaStevcaDGWS.informatika.si/")]
    public partial class odbirekResponse : object, System.ComponentModel.INotifyPropertyChanged
    {

        private System.DateTime datumOdbirkaField;

        private bool datumOdbirkaFieldSpecified;

        private short disField;

        private bool disFieldSpecified;

        private string etField;

        private int idField;

        private bool idFieldSpecified;

        private string mtField;

        private int rcField;

        private bool rcFieldSpecified;

        private int smmField;

        private bool smmFieldSpecified;

        private string sporociloField;

        private string statusField;

        private string stodField;

        private string vtField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public System.DateTime datumOdbirka
        {
            get
            {
                return this.datumOdbirkaField;
            }
            set
            {
                this.datumOdbirkaField = value;
                this.RaisePropertyChanged("datumOdbirka");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool datumOdbirkaSpecified
        {
            get
            {
                return this.datumOdbirkaFieldSpecified;
            }
            set
            {
                this.datumOdbirkaFieldSpecified = value;
                this.RaisePropertyChanged("datumOdbirkaSpecified");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public short dis
        {
            get
            {
                return this.disField;
            }
            set
            {
                this.disField = value;
                this.RaisePropertyChanged("dis");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool disSpecified
        {
            get
            {
                return this.disFieldSpecified;
            }
            set
            {
                this.disFieldSpecified = value;
                this.RaisePropertyChanged("disSpecified");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
        public string ET
        {
            get
            {
                return this.etField;
            }
            set
            {
                this.etField = value;
                this.RaisePropertyChanged("ET");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 3)]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified
        {
            get
            {
                return this.idFieldSpecified;
            }
            set
            {
                this.idFieldSpecified = value;
                this.RaisePropertyChanged("idSpecified");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 4)]
        public string MT
        {
            get
            {
                return this.mtField;
            }
            set
            {
                this.mtField = value;
                this.RaisePropertyChanged("MT");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 5)]
        public int rc
        {
            get
            {
                return this.rcField;
            }
            set
            {
                this.rcField = value;
                this.RaisePropertyChanged("rc");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool rcSpecified
        {
            get
            {
                return this.rcFieldSpecified;
            }
            set
            {
                this.rcFieldSpecified = value;
                this.RaisePropertyChanged("rcSpecified");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 6)]
        public int smm
        {
            get
            {
                return this.smmField;
            }
            set
            {
                this.smmField = value;
                this.RaisePropertyChanged("smm");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool smmSpecified
        {
            get
            {
                return this.smmFieldSpecified;
            }
            set
            {
                this.smmFieldSpecified = value;
                this.RaisePropertyChanged("smmSpecified");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 7)]
        public string sporocilo
        {
            get
            {
                return this.sporociloField;
            }
            set
            {
                this.sporociloField = value;
                this.RaisePropertyChanged("sporocilo");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 8)]
        public string status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 9)]
        public string stod
        {
            get
            {
                return this.stodField;
            }
            set
            {
                this.stodField = value;
                this.RaisePropertyChanged("stod");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 10)]
        public string VT
        {
            get
            {
                return this.vtField;
            }
            set
            {
                this.vtField = value;
                this.RaisePropertyChanged("VT");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "najdiZadnjiOdbirek", WrapperNamespace = "http://servis.vnosStanjaStevcaDGWS.informatika.si/", IsWrapped = true)]
    public partial class najdiZadnjiOdbirekRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://servis.vnosStanjaStevcaDGWS.informatika.si/", Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public short dis;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://servis.vnosStanjaStevcaDGWS.informatika.si/", Order = 1)]
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int smm;

        public najdiZadnjiOdbirekRequest()
        {
        }

        public najdiZadnjiOdbirekRequest(short dis, int smm)
        {
            this.dis = dis;
            this.smm = smm;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "najdiZadnjiOdbirekResponse", WrapperNamespace = "http://servis.vnosStanjaStevcaDGWS.informatika.si/", IsWrapped = true)]
    public partial class najdiZadnjiOdbirekResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://servis.vnosStanjaStevcaDGWS.informatika.si/", Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public KomunikatorEGP.ws_Inf_StanjeStevca.odbirekResponse @return;

        public najdiZadnjiOdbirekResponse()
        {
        }

        public najdiZadnjiOdbirekResponse(KomunikatorEGP.ws_Inf_StanjeStevca.odbirekResponse @return)
        {
            this.@return = @return;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "najdiOdbirek", WrapperNamespace = "http://servis.vnosStanjaStevcaDGWS.informatika.si/", IsWrapped = true)]
    public partial class najdiOdbirekRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://servis.vnosStanjaStevcaDGWS.informatika.si/", Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public short dis;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://servis.vnosStanjaStevcaDGWS.informatika.si/", Order = 1)]
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int smm;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://servis.vnosStanjaStevcaDGWS.informatika.si/", Order = 2)]
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime datumOdbirka;

        public najdiOdbirekRequest()
        {
        }

        public najdiOdbirekRequest(short dis, int smm, System.DateTime datumOdbirka)
        {
            this.dis = dis;
            this.smm = smm;
            this.datumOdbirka = datumOdbirka;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "najdiOdbirekResponse", WrapperNamespace = "http://servis.vnosStanjaStevcaDGWS.informatika.si/", IsWrapped = true)]
    public partial class najdiOdbirekResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://servis.vnosStanjaStevcaDGWS.informatika.si/", Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public KomunikatorEGP.ws_Inf_StanjeStevca.odbirekResponse @return;

        public najdiOdbirekResponse()
        {
        }

        public najdiOdbirekResponse(KomunikatorEGP.ws_Inf_StanjeStevca.odbirekResponse @return)
        {
            this.@return = @return;
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface StanjeStevcaChannel : KomunikatorEGP.ws_Inf_StanjeStevca.StanjeStevca, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StanjeStevcaClient : System.ServiceModel.ClientBase<KomunikatorEGP.ws_Inf_StanjeStevca.StanjeStevca>, KomunikatorEGP.ws_Inf_StanjeStevca.StanjeStevca
    {

        public StanjeStevcaClient()
        {
        }

        public StanjeStevcaClient(string endpointConfigurationName) :
            base(endpointConfigurationName)
        {
        }

        public StanjeStevcaClient(string endpointConfigurationName, string remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
        {
        }

        public StanjeStevcaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
        {
        }

        public StanjeStevcaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
            base(binding, remoteAddress)
        {
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        KomunikatorEGP.ws_Inf_StanjeStevca.poisciStaroStanjeResponse KomunikatorEGP.ws_Inf_StanjeStevca.StanjeStevca.poisciStaroStanje(KomunikatorEGP.ws_Inf_StanjeStevca.poisciStaroStanjeRequest request)
        {
            return base.Channel.poisciStaroStanje(request);
        }

        public KomunikatorEGP.ws_Inf_StanjeStevca.stanjeStevcaResponse poisciStaroStanje(KomunikatorEGP.ws_Inf_StanjeStevca.stanjeStevcaRequest arg0)
        {
            KomunikatorEGP.ws_Inf_StanjeStevca.poisciStaroStanjeRequest inValue = new KomunikatorEGP.ws_Inf_StanjeStevca.poisciStaroStanjeRequest();
            inValue.arg0 = arg0;
            KomunikatorEGP.ws_Inf_StanjeStevca.poisciStaroStanjeResponse retVal = ((KomunikatorEGP.ws_Inf_StanjeStevca.StanjeStevca)(this)).poisciStaroStanje(inValue);
            return retVal.@return;
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        KomunikatorEGP.ws_Inf_StanjeStevca.vnesiNovoStanjeResponse KomunikatorEGP.ws_Inf_StanjeStevca.StanjeStevca.vnesiNovoStanje(KomunikatorEGP.ws_Inf_StanjeStevca.vnesiNovoStanjeRequest request)
        {
            return base.Channel.vnesiNovoStanje(request);
        }

        public KomunikatorEGP.ws_Inf_StanjeStevca.vnosStanjaResponse vnesiNovoStanje(KomunikatorEGP.ws_Inf_StanjeStevca.vnosStanjaRequest arg0)
        {
            KomunikatorEGP.ws_Inf_StanjeStevca.vnesiNovoStanjeRequest inValue = new KomunikatorEGP.ws_Inf_StanjeStevca.vnesiNovoStanjeRequest();
            inValue.arg0 = arg0;
            KomunikatorEGP.ws_Inf_StanjeStevca.vnesiNovoStanjeResponse retVal = ((KomunikatorEGP.ws_Inf_StanjeStevca.StanjeStevca)(this)).vnesiNovoStanje(inValue);
            return retVal.@return;
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        KomunikatorEGP.ws_Inf_StanjeStevca.dodajKomentarResponse KomunikatorEGP.ws_Inf_StanjeStevca.StanjeStevca.dodajKomentar(KomunikatorEGP.ws_Inf_StanjeStevca.dodajKomentarRequest request)
        {
            return base.Channel.dodajKomentar(request);
        }

        public KomunikatorEGP.ws_Inf_StanjeStevca.vnosStanjaResponse dodajKomentar(int idOdbirka, string komentar)
        {
            KomunikatorEGP.ws_Inf_StanjeStevca.dodajKomentarRequest inValue = new KomunikatorEGP.ws_Inf_StanjeStevca.dodajKomentarRequest();
            inValue.idOdbirka = idOdbirka;
            inValue.komentar = komentar;
            KomunikatorEGP.ws_Inf_StanjeStevca.dodajKomentarResponse retVal = ((KomunikatorEGP.ws_Inf_StanjeStevca.StanjeStevca)(this)).dodajKomentar(inValue);
            return retVal.@return;
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        KomunikatorEGP.ws_Inf_StanjeStevca.najdiZadnjiOdbirekResponse KomunikatorEGP.ws_Inf_StanjeStevca.StanjeStevca.najdiZadnjiOdbirek(KomunikatorEGP.ws_Inf_StanjeStevca.najdiZadnjiOdbirekRequest request)
        {
            return base.Channel.najdiZadnjiOdbirek(request);
        }

        public KomunikatorEGP.ws_Inf_StanjeStevca.odbirekResponse najdiZadnjiOdbirek(short dis, int smm)
        {
            KomunikatorEGP.ws_Inf_StanjeStevca.najdiZadnjiOdbirekRequest inValue = new KomunikatorEGP.ws_Inf_StanjeStevca.najdiZadnjiOdbirekRequest();
            inValue.dis = dis;
            inValue.smm = smm;
            KomunikatorEGP.ws_Inf_StanjeStevca.najdiZadnjiOdbirekResponse retVal = ((KomunikatorEGP.ws_Inf_StanjeStevca.StanjeStevca)(this)).najdiZadnjiOdbirek(inValue);
            return retVal.@return;
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        KomunikatorEGP.ws_Inf_StanjeStevca.najdiOdbirekResponse KomunikatorEGP.ws_Inf_StanjeStevca.StanjeStevca.najdiOdbirek(KomunikatorEGP.ws_Inf_StanjeStevca.najdiOdbirekRequest request)
        {
            return base.Channel.najdiOdbirek(request);
        }

        public KomunikatorEGP.ws_Inf_StanjeStevca.odbirekResponse najdiOdbirek(short dis, int smm, System.DateTime datumOdbirka)
        {
            KomunikatorEGP.ws_Inf_StanjeStevca.najdiOdbirekRequest inValue = new KomunikatorEGP.ws_Inf_StanjeStevca.najdiOdbirekRequest();
            inValue.dis = dis;
            inValue.smm = smm;
            inValue.datumOdbirka = datumOdbirka;
            KomunikatorEGP.ws_Inf_StanjeStevca.najdiOdbirekResponse retVal = ((KomunikatorEGP.ws_Inf_StanjeStevca.StanjeStevca)(this)).najdiOdbirek(inValue);
            return retVal.@return;
        }
    }
}
