//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KomunikatorEGP.ws_Inf_ZamenjavaDobavitelja
{


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace = "http://service.ZamenjavaDobaviteljaWS.informatika.si/", ConfigurationName = "ws_Inf_ZamenjavaDobavitelja.ZamenjavaDobaviteljaWS")]
    public interface ZamenjavaDobaviteljaWS
    {

        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action = "", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name = "return")]
        KomunikatorEGP.ws_Inf_ZamenjavaDobavitelja.oddajZahtevoResponse oddajZahtevo(KomunikatorEGP.ws_Inf_ZamenjavaDobavitelja.oddajZahtevoRequest request);

        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action = "", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name = "return")]
        KomunikatorEGP.ws_Inf_ZamenjavaDobavitelja.najdiZahtevoResponse najdiZahtevo(KomunikatorEGP.ws_Inf_ZamenjavaDobavitelja.najdiZahtevoRequest request);

        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action = "", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name = "return")]
        KomunikatorEGP.ws_Inf_ZamenjavaDobavitelja.najdiZahtevoPlusResponse najdiZahtevoPlus(KomunikatorEGP.ws_Inf_ZamenjavaDobavitelja.najdiZahtevoPlusRequest request);

        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action = "", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name = "return")]
        KomunikatorEGP.ws_Inf_ZamenjavaDobavitelja.najdiSeznamZahtevResponse najdiSeznamZahtev(KomunikatorEGP.ws_Inf_ZamenjavaDobavitelja.najdiSeznamZahtevRequest request);
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://service.ZamenjavaDobaviteljaWS.informatika.si/")]
    public partial class oddajZahtevoZahtevek : object, System.ComponentModel.INotifyPropertyChanged
    {

        private System.DateTime datumKoncaField;

        private bool datumKoncaFieldSpecified;

        private System.DateTime datunZacetkaField;

        private bool datunZacetkaFieldSpecified;

        private string davcnaStField;

        private short disField;

        private string imePrilogeField;

        private int konicnaObremenitevField;

        private bool placevanjeUporabeOmrezjaField;

        private int prenosEnergijeField;

        private byte[] prilogaField;

        private int smmField;

        private string tipPrilogeField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public System.DateTime datumKonca
        {
            get
            {
                return this.datumKoncaField;
            }
            set
            {
                this.datumKoncaField = value;
                this.RaisePropertyChanged("datumKonca");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool datumKoncaSpecified
        {
            get
            {
                return this.datumKoncaFieldSpecified;
            }
            set
            {
                this.datumKoncaFieldSpecified = value;
                this.RaisePropertyChanged("datumKoncaSpecified");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public System.DateTime datunZacetka
        {
            get
            {
                return this.datunZacetkaField;
            }
            set
            {
                this.datunZacetkaField = value;
                this.RaisePropertyChanged("datunZacetka");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool datunZacetkaSpecified
        {
            get
            {
                return this.datunZacetkaFieldSpecified;
            }
            set
            {
                this.datunZacetkaFieldSpecified = value;
                this.RaisePropertyChanged("datunZacetkaSpecified");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
        public string davcnaSt
        {
            get
            {
                return this.davcnaStField;
            }
            set
            {
                this.davcnaStField = value;
                this.RaisePropertyChanged("davcnaSt");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 3)]
        public short dis
        {
            get
            {
                return this.disField;
            }
            set
            {
                this.disField = value;
                this.RaisePropertyChanged("dis");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 4)]
        public string imePriloge
        {
            get
            {
                return this.imePrilogeField;
            }
            set
            {
                this.imePrilogeField = value;
                this.RaisePropertyChanged("imePriloge");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 5)]
        public int konicnaObremenitev
        {
            get
            {
                return this.konicnaObremenitevField;
            }
            set
            {
                this.konicnaObremenitevField = value;
                this.RaisePropertyChanged("konicnaObremenitev");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 6)]
        public bool placevanjeUporabeOmrezja
        {
            get
            {
                return this.placevanjeUporabeOmrezjaField;
            }
            set
            {
                this.placevanjeUporabeOmrezjaField = value;
                this.RaisePropertyChanged("placevanjeUporabeOmrezja");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 7)]
        public int prenosEnergije
        {
            get
            {
                return this.prenosEnergijeField;
            }
            set
            {
                this.prenosEnergijeField = value;
                this.RaisePropertyChanged("prenosEnergije");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "base64Binary", Order = 8)]
        public byte[] priloga
        {
            get
            {
                return this.prilogaField;
            }
            set
            {
                this.prilogaField = value;
                this.RaisePropertyChanged("priloga");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 9)]
        public int smm
        {
            get
            {
                return this.smmField;
            }
            set
            {
                this.smmField = value;
                this.RaisePropertyChanged("smm");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 10)]
        public string tipPriloge
        {
            get
            {
                return this.tipPrilogeField;
            }
            set
            {
                this.tipPrilogeField = value;
                this.RaisePropertyChanged("tipPriloge");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://service.ZamenjavaDobaviteljaWS.informatika.si/")]
    public partial class seznamZahtevOdgovor : object, System.ComponentModel.INotifyPropertyChanged
    {

        private string msgField;

        private int rcField;

        private zahtevaOdgovor[] seznamZahtevField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public string msg
        {
            get
            {
                return this.msgField;
            }
            set
            {
                this.msgField = value;
                this.RaisePropertyChanged("msg");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public int rc
        {
            get
            {
                return this.rcField;
            }
            set
            {
                this.rcField = value;
                this.RaisePropertyChanged("rc");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("seznamZahtev", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true, Order = 2)]
        public zahtevaOdgovor[] seznamZahtev
        {
            get
            {
                return this.seznamZahtevField;
            }
            set
            {
                this.seznamZahtevField = value;
                this.RaisePropertyChanged("seznamZahtev");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://service.ZamenjavaDobaviteljaWS.informatika.si/")]
    public partial class zahtevaOdgovor : object, System.ComponentModel.INotifyPropertyChanged
    {

        private System.DateTime datumKoncaDostopaField;

        private bool datumKoncaDostopaFieldSpecified;

        private System.DateTime datumOddajeZahteveField;

        private bool datumOddajeZahteveFieldSpecified;

        private System.DateTime datumSpremembeField;

        private bool datumSpremembeFieldSpecified;

        private System.DateTime datumZacetkaDostopaField;

        private bool datumZacetkaDostopaFieldSpecified;

        private string davcnaStField;

        private short disField;

        private dodatniPodatki dodatniPodatkiField;

        private int idField;

        private string msgField;

        private int rcField;

        private int sifraDobaviteljaField;

        private int sifraPlacnikaField;

        private int sifraPravneOsebeField;

        private bool sifraPravneOsebeFieldSpecified;

        private int smmField;

        private int statusZahteveField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public System.DateTime datumKoncaDostopa
        {
            get
            {
                return this.datumKoncaDostopaField;
            }
            set
            {
                this.datumKoncaDostopaField = value;
                this.RaisePropertyChanged("datumKoncaDostopa");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool datumKoncaDostopaSpecified
        {
            get
            {
                return this.datumKoncaDostopaFieldSpecified;
            }
            set
            {
                this.datumKoncaDostopaFieldSpecified = value;
                this.RaisePropertyChanged("datumKoncaDostopaSpecified");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public System.DateTime datumOddajeZahteve
        {
            get
            {
                return this.datumOddajeZahteveField;
            }
            set
            {
                this.datumOddajeZahteveField = value;
                this.RaisePropertyChanged("datumOddajeZahteve");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool datumOddajeZahteveSpecified
        {
            get
            {
                return this.datumOddajeZahteveFieldSpecified;
            }
            set
            {
                this.datumOddajeZahteveFieldSpecified = value;
                this.RaisePropertyChanged("datumOddajeZahteveSpecified");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
        public System.DateTime datumSpremembe
        {
            get
            {
                return this.datumSpremembeField;
            }
            set
            {
                this.datumSpremembeField = value;
                this.RaisePropertyChanged("datumSpremembe");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool datumSpremembeSpecified
        {
            get
            {
                return this.datumSpremembeFieldSpecified;
            }
            set
            {
                this.datumSpremembeFieldSpecified = value;
                this.RaisePropertyChanged("datumSpremembeSpecified");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 3)]
        public System.DateTime datumZacetkaDostopa
        {
            get
            {
                return this.datumZacetkaDostopaField;
            }
            set
            {
                this.datumZacetkaDostopaField = value;
                this.RaisePropertyChanged("datumZacetkaDostopa");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool datumZacetkaDostopaSpecified
        {
            get
            {
                return this.datumZacetkaDostopaFieldSpecified;
            }
            set
            {
                this.datumZacetkaDostopaFieldSpecified = value;
                this.RaisePropertyChanged("datumZacetkaDostopaSpecified");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 4)]
        public string davcnaSt
        {
            get
            {
                return this.davcnaStField;
            }
            set
            {
                this.davcnaStField = value;
                this.RaisePropertyChanged("davcnaSt");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 5)]
        public short dis
        {
            get
            {
                return this.disField;
            }
            set
            {
                this.disField = value;
                this.RaisePropertyChanged("dis");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 6)]
        public dodatniPodatki dodatniPodatki
        {
            get
            {
                return this.dodatniPodatkiField;
            }
            set
            {
                this.dodatniPodatkiField = value;
                this.RaisePropertyChanged("dodatniPodatki");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 7)]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 8)]
        public string msg
        {
            get
            {
                return this.msgField;
            }
            set
            {
                this.msgField = value;
                this.RaisePropertyChanged("msg");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 9)]
        public int rc
        {
            get
            {
                return this.rcField;
            }
            set
            {
                this.rcField = value;
                this.RaisePropertyChanged("rc");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 10)]
        public int sifraDobavitelja
        {
            get
            {
                return this.sifraDobaviteljaField;
            }
            set
            {
                this.sifraDobaviteljaField = value;
                this.RaisePropertyChanged("sifraDobavitelja");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 11)]
        public int sifraPlacnika
        {
            get
            {
                return this.sifraPlacnikaField;
            }
            set
            {
                this.sifraPlacnikaField = value;
                this.RaisePropertyChanged("sifraPlacnika");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 12)]
        public int sifraPravneOsebe
        {
            get
            {
                return this.sifraPravneOsebeField;
            }
            set
            {
                this.sifraPravneOsebeField = value;
                this.RaisePropertyChanged("sifraPravneOsebe");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool sifraPravneOsebeSpecified
        {
            get
            {
                return this.sifraPravneOsebeFieldSpecified;
            }
            set
            {
                this.sifraPravneOsebeFieldSpecified = value;
                this.RaisePropertyChanged("sifraPravneOsebeSpecified");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 13)]
        public int smm
        {
            get
            {
                return this.smmField;
            }
            set
            {
                this.smmField = value;
                this.RaisePropertyChanged("smm");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 14)]
        public int statusZahteve
        {
            get
            {
                return this.statusZahteveField;
            }
            set
            {
                this.statusZahteveField = value;
                this.RaisePropertyChanged("statusZahteve");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://service.ZamenjavaDobaviteljaWS.informatika.si/")]
    public partial class dodatniPodatki : object, System.ComponentModel.INotifyPropertyChanged
    {

        private int energijaMTField;

        private bool energijaMTFieldSpecified;

        private int energijaVTField;

        private bool energijaVTFieldSpecified;

        private int mocIzSoglasjaField;

        private bool mocIzSoglasjaFieldSpecified;

        private int obracunskaMocField;

        private bool obracunskaMocFieldSpecified;

        private string obracunskaVarovalkaField;

        private int tarifnaSkupinaField;

        private bool tarifnaSkupinaFieldSpecified;

        private int vrstaObracunaField;

        private bool vrstaObracunaFieldSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public int energijaMT
        {
            get
            {
                return this.energijaMTField;
            }
            set
            {
                this.energijaMTField = value;
                this.RaisePropertyChanged("energijaMT");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool energijaMTSpecified
        {
            get
            {
                return this.energijaMTFieldSpecified;
            }
            set
            {
                this.energijaMTFieldSpecified = value;
                this.RaisePropertyChanged("energijaMTSpecified");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public int energijaVT
        {
            get
            {
                return this.energijaVTField;
            }
            set
            {
                this.energijaVTField = value;
                this.RaisePropertyChanged("energijaVT");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool energijaVTSpecified
        {
            get
            {
                return this.energijaVTFieldSpecified;
            }
            set
            {
                this.energijaVTFieldSpecified = value;
                this.RaisePropertyChanged("energijaVTSpecified");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
        public int mocIzSoglasja
        {
            get
            {
                return this.mocIzSoglasjaField;
            }
            set
            {
                this.mocIzSoglasjaField = value;
                this.RaisePropertyChanged("mocIzSoglasja");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool mocIzSoglasjaSpecified
        {
            get
            {
                return this.mocIzSoglasjaFieldSpecified;
            }
            set
            {
                this.mocIzSoglasjaFieldSpecified = value;
                this.RaisePropertyChanged("mocIzSoglasjaSpecified");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 3)]
        public int obracunskaMoc
        {
            get
            {
                return this.obracunskaMocField;
            }
            set
            {
                this.obracunskaMocField = value;
                this.RaisePropertyChanged("obracunskaMoc");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool obracunskaMocSpecified
        {
            get
            {
                return this.obracunskaMocFieldSpecified;
            }
            set
            {
                this.obracunskaMocFieldSpecified = value;
                this.RaisePropertyChanged("obracunskaMocSpecified");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 4)]
        public string obracunskaVarovalka
        {
            get
            {
                return this.obracunskaVarovalkaField;
            }
            set
            {
                this.obracunskaVarovalkaField = value;
                this.RaisePropertyChanged("obracunskaVarovalka");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 5)]
        public int tarifnaSkupina
        {
            get
            {
                return this.tarifnaSkupinaField;
            }
            set
            {
                this.tarifnaSkupinaField = value;
                this.RaisePropertyChanged("tarifnaSkupina");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tarifnaSkupinaSpecified
        {
            get
            {
                return this.tarifnaSkupinaFieldSpecified;
            }
            set
            {
                this.tarifnaSkupinaFieldSpecified = value;
                this.RaisePropertyChanged("tarifnaSkupinaSpecified");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 6)]
        public int vrstaObracuna
        {
            get
            {
                return this.vrstaObracunaField;
            }
            set
            {
                this.vrstaObracunaField = value;
                this.RaisePropertyChanged("vrstaObracuna");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool vrstaObracunaSpecified
        {
            get
            {
                return this.vrstaObracunaFieldSpecified;
            }
            set
            {
                this.vrstaObracunaFieldSpecified = value;
                this.RaisePropertyChanged("vrstaObracunaSpecified");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://service.ZamenjavaDobaviteljaWS.informatika.si/")]
    public partial class seznamZahtevZahtevek : object, System.ComponentModel.INotifyPropertyChanged
    {

        private System.DateTime datumDoField;

        private bool datumDoFieldSpecified;

        private System.DateTime datumOdField;

        private bool datumOdFieldSpecified;

        private int sTATUS_ZAHTEVField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public System.DateTime datumDo
        {
            get
            {
                return this.datumDoField;
            }
            set
            {
                this.datumDoField = value;
                this.RaisePropertyChanged("datumDo");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool datumDoSpecified
        {
            get
            {
                return this.datumDoFieldSpecified;
            }
            set
            {
                this.datumDoFieldSpecified = value;
                this.RaisePropertyChanged("datumDoSpecified");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public System.DateTime datumOd
        {
            get
            {
                return this.datumOdField;
            }
            set
            {
                this.datumOdField = value;
                this.RaisePropertyChanged("datumOd");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool datumOdSpecified
        {
            get
            {
                return this.datumOdFieldSpecified;
            }
            set
            {
                this.datumOdFieldSpecified = value;
                this.RaisePropertyChanged("datumOdSpecified");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
        public int STATUS_ZAHTEV
        {
            get
            {
                return this.sTATUS_ZAHTEVField;
            }
            set
            {
                this.sTATUS_ZAHTEVField = value;
                this.RaisePropertyChanged("STATUS_ZAHTEV");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://service.ZamenjavaDobaviteljaWS.informatika.si/")]
    public partial class oddajZahtevoOdgovor : object, System.ComponentModel.INotifyPropertyChanged
    {

        private string msgField;

        private int rcField;

        private int zahtevaIdField;

        private bool zahtevaIdFieldSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public string msg
        {
            get
            {
                return this.msgField;
            }
            set
            {
                this.msgField = value;
                this.RaisePropertyChanged("msg");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public int rc
        {
            get
            {
                return this.rcField;
            }
            set
            {
                this.rcField = value;
                this.RaisePropertyChanged("rc");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
        public int zahtevaId
        {
            get
            {
                return this.zahtevaIdField;
            }
            set
            {
                this.zahtevaIdField = value;
                this.RaisePropertyChanged("zahtevaId");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool zahtevaIdSpecified
        {
            get
            {
                return this.zahtevaIdFieldSpecified;
            }
            set
            {
                this.zahtevaIdFieldSpecified = value;
                this.RaisePropertyChanged("zahtevaIdSpecified");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "oddajZahtevo", WrapperNamespace = "http://service.ZamenjavaDobaviteljaWS.informatika.si/", IsWrapped = true)]
    public partial class oddajZahtevoRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://service.ZamenjavaDobaviteljaWS.informatika.si/", Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public KomunikatorEGP.ws_Inf_ZamenjavaDobavitelja.oddajZahtevoZahtevek arg0;

        public oddajZahtevoRequest()
        {
        }

        public oddajZahtevoRequest(KomunikatorEGP.ws_Inf_ZamenjavaDobavitelja.oddajZahtevoZahtevek arg0)
        {
            this.arg0 = arg0;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "oddajZahtevoResponse", WrapperNamespace = "http://service.ZamenjavaDobaviteljaWS.informatika.si/", IsWrapped = true)]
    public partial class oddajZahtevoResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://service.ZamenjavaDobaviteljaWS.informatika.si/", Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public KomunikatorEGP.ws_Inf_ZamenjavaDobavitelja.oddajZahtevoOdgovor @return;

        public oddajZahtevoResponse()
        {
        }

        public oddajZahtevoResponse(KomunikatorEGP.ws_Inf_ZamenjavaDobavitelja.oddajZahtevoOdgovor @return)
        {
            this.@return = @return;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "najdiZahtevo", WrapperNamespace = "http://service.ZamenjavaDobaviteljaWS.informatika.si/", IsWrapped = true)]
    public partial class najdiZahtevoRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://service.ZamenjavaDobaviteljaWS.informatika.si/", Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg0;

        public najdiZahtevoRequest()
        {
        }

        public najdiZahtevoRequest(int arg0)
        {
            this.arg0 = arg0;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "najdiZahtevoResponse", WrapperNamespace = "http://service.ZamenjavaDobaviteljaWS.informatika.si/", IsWrapped = true)]
    public partial class najdiZahtevoResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://service.ZamenjavaDobaviteljaWS.informatika.si/", Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public KomunikatorEGP.ws_Inf_ZamenjavaDobavitelja.zahtevaOdgovor @return;

        public najdiZahtevoResponse()
        {
        }

        public najdiZahtevoResponse(KomunikatorEGP.ws_Inf_ZamenjavaDobavitelja.zahtevaOdgovor @return)
        {
            this.@return = @return;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "najdiZahtevoPlus", WrapperNamespace = "http://service.ZamenjavaDobaviteljaWS.informatika.si/", IsWrapped = true)]
    public partial class najdiZahtevoPlusRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://service.ZamenjavaDobaviteljaWS.informatika.si/", Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int zahtevaId;

        public najdiZahtevoPlusRequest()
        {
        }

        public najdiZahtevoPlusRequest(int zahtevaId)
        {
            this.zahtevaId = zahtevaId;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "najdiZahtevoPlusResponse", WrapperNamespace = "http://service.ZamenjavaDobaviteljaWS.informatika.si/", IsWrapped = true)]
    public partial class najdiZahtevoPlusResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://service.ZamenjavaDobaviteljaWS.informatika.si/", Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public KomunikatorEGP.ws_Inf_ZamenjavaDobavitelja.zahtevaOdgovor @return;

        public najdiZahtevoPlusResponse()
        {
        }

        public najdiZahtevoPlusResponse(KomunikatorEGP.ws_Inf_ZamenjavaDobavitelja.zahtevaOdgovor @return)
        {
            this.@return = @return;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "najdiSeznamZahtev", WrapperNamespace = "http://service.ZamenjavaDobaviteljaWS.informatika.si/", IsWrapped = true)]
    public partial class najdiSeznamZahtevRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://service.ZamenjavaDobaviteljaWS.informatika.si/", Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public KomunikatorEGP.ws_Inf_ZamenjavaDobavitelja.seznamZahtevZahtevek arg0;

        public najdiSeznamZahtevRequest()
        {
        }

        public najdiSeznamZahtevRequest(KomunikatorEGP.ws_Inf_ZamenjavaDobavitelja.seznamZahtevZahtevek arg0)
        {
            this.arg0 = arg0;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "najdiSeznamZahtevResponse", WrapperNamespace = "http://service.ZamenjavaDobaviteljaWS.informatika.si/", IsWrapped = true)]
    public partial class najdiSeznamZahtevResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://service.ZamenjavaDobaviteljaWS.informatika.si/", Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public KomunikatorEGP.ws_Inf_ZamenjavaDobavitelja.seznamZahtevOdgovor @return;

        public najdiSeznamZahtevResponse()
        {
        }

        public najdiSeznamZahtevResponse(KomunikatorEGP.ws_Inf_ZamenjavaDobavitelja.seznamZahtevOdgovor @return)
        {
            this.@return = @return;
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ZamenjavaDobaviteljaWSChannel : KomunikatorEGP.ws_Inf_ZamenjavaDobavitelja.ZamenjavaDobaviteljaWS, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ZamenjavaDobaviteljaWSClient : System.ServiceModel.ClientBase<KomunikatorEGP.ws_Inf_ZamenjavaDobavitelja.ZamenjavaDobaviteljaWS>, KomunikatorEGP.ws_Inf_ZamenjavaDobavitelja.ZamenjavaDobaviteljaWS
    {

        public ZamenjavaDobaviteljaWSClient()
        {
        }

        public ZamenjavaDobaviteljaWSClient(string endpointConfigurationName) :
            base(endpointConfigurationName)
        {
        }

        public ZamenjavaDobaviteljaWSClient(string endpointConfigurationName, string remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
        {
        }

        public ZamenjavaDobaviteljaWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
        {
        }

        public ZamenjavaDobaviteljaWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
            base(binding, remoteAddress)
        {
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        KomunikatorEGP.ws_Inf_ZamenjavaDobavitelja.oddajZahtevoResponse KomunikatorEGP.ws_Inf_ZamenjavaDobavitelja.ZamenjavaDobaviteljaWS.oddajZahtevo(KomunikatorEGP.ws_Inf_ZamenjavaDobavitelja.oddajZahtevoRequest request)
        {
            return base.Channel.oddajZahtevo(request);
        }

        public KomunikatorEGP.ws_Inf_ZamenjavaDobavitelja.oddajZahtevoOdgovor oddajZahtevo(KomunikatorEGP.ws_Inf_ZamenjavaDobavitelja.oddajZahtevoZahtevek arg0)
        {
            KomunikatorEGP.ws_Inf_ZamenjavaDobavitelja.oddajZahtevoRequest inValue = new KomunikatorEGP.ws_Inf_ZamenjavaDobavitelja.oddajZahtevoRequest();
            inValue.arg0 = arg0;
            KomunikatorEGP.ws_Inf_ZamenjavaDobavitelja.oddajZahtevoResponse retVal = ((KomunikatorEGP.ws_Inf_ZamenjavaDobavitelja.ZamenjavaDobaviteljaWS)(this)).oddajZahtevo(inValue);
            return retVal.@return;
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        KomunikatorEGP.ws_Inf_ZamenjavaDobavitelja.najdiZahtevoResponse KomunikatorEGP.ws_Inf_ZamenjavaDobavitelja.ZamenjavaDobaviteljaWS.najdiZahtevo(KomunikatorEGP.ws_Inf_ZamenjavaDobavitelja.najdiZahtevoRequest request)
        {
            return base.Channel.najdiZahtevo(request);
        }

        public KomunikatorEGP.ws_Inf_ZamenjavaDobavitelja.zahtevaOdgovor najdiZahtevo(int arg0)
        {
            KomunikatorEGP.ws_Inf_ZamenjavaDobavitelja.najdiZahtevoRequest inValue = new KomunikatorEGP.ws_Inf_ZamenjavaDobavitelja.najdiZahtevoRequest();
            inValue.arg0 = arg0;
            KomunikatorEGP.ws_Inf_ZamenjavaDobavitelja.najdiZahtevoResponse retVal = ((KomunikatorEGP.ws_Inf_ZamenjavaDobavitelja.ZamenjavaDobaviteljaWS)(this)).najdiZahtevo(inValue);
            return retVal.@return;
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        KomunikatorEGP.ws_Inf_ZamenjavaDobavitelja.najdiZahtevoPlusResponse KomunikatorEGP.ws_Inf_ZamenjavaDobavitelja.ZamenjavaDobaviteljaWS.najdiZahtevoPlus(KomunikatorEGP.ws_Inf_ZamenjavaDobavitelja.najdiZahtevoPlusRequest request)
        {
            return base.Channel.najdiZahtevoPlus(request);
        }

        public KomunikatorEGP.ws_Inf_ZamenjavaDobavitelja.zahtevaOdgovor najdiZahtevoPlus(int zahtevaId)
        {
            KomunikatorEGP.ws_Inf_ZamenjavaDobavitelja.najdiZahtevoPlusRequest inValue = new KomunikatorEGP.ws_Inf_ZamenjavaDobavitelja.najdiZahtevoPlusRequest();
            inValue.zahtevaId = zahtevaId;
            KomunikatorEGP.ws_Inf_ZamenjavaDobavitelja.najdiZahtevoPlusResponse retVal = ((KomunikatorEGP.ws_Inf_ZamenjavaDobavitelja.ZamenjavaDobaviteljaWS)(this)).najdiZahtevoPlus(inValue);
            return retVal.@return;
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        KomunikatorEGP.ws_Inf_ZamenjavaDobavitelja.najdiSeznamZahtevResponse KomunikatorEGP.ws_Inf_ZamenjavaDobavitelja.ZamenjavaDobaviteljaWS.najdiSeznamZahtev(KomunikatorEGP.ws_Inf_ZamenjavaDobavitelja.najdiSeznamZahtevRequest request)
        {
            return base.Channel.najdiSeznamZahtev(request);
        }

        public KomunikatorEGP.ws_Inf_ZamenjavaDobavitelja.seznamZahtevOdgovor najdiSeznamZahtev(KomunikatorEGP.ws_Inf_ZamenjavaDobavitelja.seznamZahtevZahtevek arg0)
        {
            KomunikatorEGP.ws_Inf_ZamenjavaDobavitelja.najdiSeznamZahtevRequest inValue = new KomunikatorEGP.ws_Inf_ZamenjavaDobavitelja.najdiSeznamZahtevRequest();
            inValue.arg0 = arg0;
            KomunikatorEGP.ws_Inf_ZamenjavaDobavitelja.najdiSeznamZahtevResponse retVal = ((KomunikatorEGP.ws_Inf_ZamenjavaDobavitelja.ZamenjavaDobaviteljaWS)(this)).najdiSeznamZahtev(inValue);
            return retVal.@return;
        }
    }
}
