//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KroClientLib.KroFaktureService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Vhod", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class Vhod : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdTipField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Ime_XMLField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PosiljateljField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Vsebina_XMLField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdTip {
            get {
                return this.IdTipField;
            }
            set {
                if ((this.IdTipField.Equals(value) != true)) {
                    this.IdTipField = value;
                    this.RaisePropertyChanged("IdTip");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ime_XML {
            get {
                return this.Ime_XMLField;
            }
            set {
                if ((object.ReferenceEquals(this.Ime_XMLField, value) != true)) {
                    this.Ime_XMLField = value;
                    this.RaisePropertyChanged("Ime_XML");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Posiljatelj {
            get {
                return this.PosiljateljField;
            }
            set {
                if ((object.ReferenceEquals(this.PosiljateljField, value) != true)) {
                    this.PosiljateljField = value;
                    this.RaisePropertyChanged("Posiljatelj");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Vsebina_XML {
            get {
                return this.Vsebina_XMLField;
            }
            set {
                if ((object.ReferenceEquals(this.Vsebina_XMLField, value) != true)) {
                    this.Vsebina_XMLField = value;
                    this.RaisePropertyChanged("Vsebina_XML");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Izhod", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class Izhod : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] Datoteka_ByteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long File_SizeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdTipField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Ime_PDFField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PosiljateljField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private KroClientLib.KroFaktureService.Stanje StanjeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Datoteka_Byte {
            get {
                return this.Datoteka_ByteField;
            }
            set {
                if ((object.ReferenceEquals(this.Datoteka_ByteField, value) != true)) {
                    this.Datoteka_ByteField = value;
                    this.RaisePropertyChanged("Datoteka_Byte");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long File_Size {
            get {
                return this.File_SizeField;
            }
            set {
                if ((this.File_SizeField.Equals(value) != true)) {
                    this.File_SizeField = value;
                    this.RaisePropertyChanged("File_Size");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdTip {
            get {
                return this.IdTipField;
            }
            set {
                if ((this.IdTipField.Equals(value) != true)) {
                    this.IdTipField = value;
                    this.RaisePropertyChanged("IdTip");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ime_PDF {
            get {
                return this.Ime_PDFField;
            }
            set {
                if ((object.ReferenceEquals(this.Ime_PDFField, value) != true)) {
                    this.Ime_PDFField = value;
                    this.RaisePropertyChanged("Ime_PDF");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Posiljatelj {
            get {
                return this.PosiljateljField;
            }
            set {
                if ((object.ReferenceEquals(this.PosiljateljField, value) != true)) {
                    this.PosiljateljField = value;
                    this.RaisePropertyChanged("Posiljatelj");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public KroClientLib.KroFaktureService.Stanje Stanje {
            get {
                return this.StanjeField;
            }
            set {
                if ((object.ReferenceEquals(this.StanjeField, value) != true)) {
                    this.StanjeField = value;
                    this.RaisePropertyChanged("Stanje");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Stanje", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class Stanje : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OpisField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StanjeMemberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Opis {
            get {
                return this.OpisField;
            }
            set {
                if ((object.ReferenceEquals(this.OpisField, value) != true)) {
                    this.OpisField = value;
                    this.RaisePropertyChanged("Opis");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="Stanje")]
        public int StanjeMember {
            get {
                return this.StanjeMemberField;
            }
            set {
                if ((this.StanjeMemberField.Equals(value) != true)) {
                    this.StanjeMemberField = value;
                    this.RaisePropertyChanged("StanjeMember");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Prevzeto", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class Prevzeto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdTipField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Ime_PDFField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OdgovorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Opis_NapakeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PosiljateljField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdTip {
            get {
                return this.IdTipField;
            }
            set {
                if ((this.IdTipField.Equals(value) != true)) {
                    this.IdTipField = value;
                    this.RaisePropertyChanged("IdTip");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ime_PDF {
            get {
                return this.Ime_PDFField;
            }
            set {
                if ((object.ReferenceEquals(this.Ime_PDFField, value) != true)) {
                    this.Ime_PDFField = value;
                    this.RaisePropertyChanged("Ime_PDF");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Odgovor {
            get {
                return this.OdgovorField;
            }
            set {
                if ((this.OdgovorField.Equals(value) != true)) {
                    this.OdgovorField = value;
                    this.RaisePropertyChanged("Odgovor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Opis_Napake {
            get {
                return this.Opis_NapakeField;
            }
            set {
                if ((object.ReferenceEquals(this.Opis_NapakeField, value) != true)) {
                    this.Opis_NapakeField = value;
                    this.RaisePropertyChanged("Opis_Napake");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Posiljatelj {
            get {
                return this.PosiljateljField;
            }
            set {
                if ((object.ReferenceEquals(this.PosiljateljField, value) != true)) {
                    this.PosiljateljField = value;
                    this.RaisePropertyChanged("Posiljatelj");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="KroFaktureService.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetCon", ReplyAction="http://tempuri.org/IService/GetConResponse")]
        string GetCon(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/Vhodni_xml", ReplyAction="http://tempuri.org/IService/Vhodni_xmlResponse")]
        KroClientLib.KroFaktureService.Izhod Vhodni_xml(KroClientLib.KroFaktureService.Vhod vhodni);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/Stanje_Servisa", ReplyAction="http://tempuri.org/IService/Stanje_ServisaResponse")]
        KroClientLib.KroFaktureService.Stanje Stanje_Servisa();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/Datoteka_Prevzeta", ReplyAction="http://tempuri.org/IService/Datoteka_PrevzetaResponse")]
        KroClientLib.KroFaktureService.Stanje Datoteka_Prevzeta(KroClientLib.KroFaktureService.Prevzeto odgovor);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : KroClientLib.KroFaktureService.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<KroClientLib.KroFaktureService.IService>, KroClientLib.KroFaktureService.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetCon(int value) {
            return base.Channel.GetCon(value);
        }
        
        public KroClientLib.KroFaktureService.Izhod Vhodni_xml(KroClientLib.KroFaktureService.Vhod vhodni) {
            return base.Channel.Vhodni_xml(vhodni);
        }
        
        public KroClientLib.KroFaktureService.Stanje Stanje_Servisa() {
            return base.Channel.Stanje_Servisa();
        }
        
        public KroClientLib.KroFaktureService.Stanje Datoteka_Prevzeta(KroClientLib.KroFaktureService.Prevzeto odgovor) {
            return base.Channel.Datoteka_Prevzeta(odgovor);
        }
    }
}
