//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class DOCUMENTS {
    
    private DOCUMENT[] dOCUMENTField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("DOCUMENT")]
    public DOCUMENT[] DOCUMENT {
        get {
            return this.dOCUMENTField;
        }
        set {
            this.dOCUMENTField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class DOCUMENT {
    
    private int idField;
    
    private bool idFieldSpecified;
    
    private string eXTERNAL_IDField;
    
    private string tITLEField;
    
    private System.DateTime cREATION_TIMEField;
    
    private bool cREATION_TIMEFieldSpecified;
    
    private string cREATION_LOCATIONField;
    
    private string fILENAMEField;
    
    private string mIMETYPEField;
    
    private string oRGANIZATIONField;
    
    private System.DateTime iNSERT_DATEField;
    
    private bool iNSERT_DATEFieldSpecified;
    
    private string cLASSIFICATION_NAMEField;
    
    private string aCCOUNT_NAMEField;
    
    private string uSR_IDField;
    
    private string sTATUSField;
    
    private string uSR_ID_UPORABNIKField;
    
    private int sIZEField;
    
    private bool sIZEFieldSpecified;
    
    private string tYPEField;
    
    private int aCC_IDField;
    
    private bool aCC_IDFieldSpecified;
    
    private string vER_DESCRIPTIONField;
    
    private int dOC_IDField;
    
    private bool dOC_IDFieldSpecified;
    
    private string dATA_REFERENCEField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int ID {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool IDSpecified {
        get {
            return this.idFieldSpecified;
        }
        set {
            this.idFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string EXTERNAL_ID {
        get {
            return this.eXTERNAL_IDField;
        }
        set {
            this.eXTERNAL_IDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string TITLE {
        get {
            return this.tITLEField;
        }
        set {
            this.tITLEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public System.DateTime CREATION_TIME {
        get {
            return this.cREATION_TIMEField;
        }
        set {
            this.cREATION_TIMEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool CREATION_TIMESpecified {
        get {
            return this.cREATION_TIMEFieldSpecified;
        }
        set {
            this.cREATION_TIMEFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CREATION_LOCATION {
        get {
            return this.cREATION_LOCATIONField;
        }
        set {
            this.cREATION_LOCATIONField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string FILENAME {
        get {
            return this.fILENAMEField;
        }
        set {
            this.fILENAMEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string MIMETYPE {
        get {
            return this.mIMETYPEField;
        }
        set {
            this.mIMETYPEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ORGANIZATION {
        get {
            return this.oRGANIZATIONField;
        }
        set {
            this.oRGANIZATIONField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public System.DateTime INSERT_DATE {
        get {
            return this.iNSERT_DATEField;
        }
        set {
            this.iNSERT_DATEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool INSERT_DATESpecified {
        get {
            return this.iNSERT_DATEFieldSpecified;
        }
        set {
            this.iNSERT_DATEFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CLASSIFICATION_NAME {
        get {
            return this.cLASSIFICATION_NAMEField;
        }
        set {
            this.cLASSIFICATION_NAMEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ACCOUNT_NAME {
        get {
            return this.aCCOUNT_NAMEField;
        }
        set {
            this.aCCOUNT_NAMEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string USR_ID {
        get {
            return this.uSR_IDField;
        }
        set {
            this.uSR_IDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string STATUS {
        get {
            return this.sTATUSField;
        }
        set {
            this.sTATUSField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string USR_ID_UPORABNIK {
        get {
            return this.uSR_ID_UPORABNIKField;
        }
        set {
            this.uSR_ID_UPORABNIKField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int SIZE {
        get {
            return this.sIZEField;
        }
        set {
            this.sIZEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool SIZESpecified {
        get {
            return this.sIZEFieldSpecified;
        }
        set {
            this.sIZEFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string TYPE {
        get {
            return this.tYPEField;
        }
        set {
            this.tYPEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int ACC_ID {
        get {
            return this.aCC_IDField;
        }
        set {
            this.aCC_IDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ACC_IDSpecified {
        get {
            return this.aCC_IDFieldSpecified;
        }
        set {
            this.aCC_IDFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string VER_DESCRIPTION {
        get {
            return this.vER_DESCRIPTIONField;
        }
        set {
            this.vER_DESCRIPTIONField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int DOC_ID {
        get {
            return this.dOC_IDField;
        }
        set {
            this.dOC_IDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool DOC_IDSpecified {
        get {
            return this.dOC_IDFieldSpecified;
        }
        set {
            this.dOC_IDFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string DATA_REFERENCE {
        get {
            return this.dATA_REFERENCEField;
        }
        set {
            this.dATA_REFERENCEField = value;
        }
    }

}
